### ISSUE TITLE
fresh termux install: package verification issues

### ISSUE THREAD

**Issue by redthing1** [TermuxArch/TermuxArch#100]
fresh termux install on a new Samsung
Android 12

![Screenshot_20230106-170550_Termux](https://user-images.githubusercontent.com/54390138/211124146-628ea9ec-b42a-4086-b23f-be81a3b76d01.jpg)

**Comment by SmuggyAsshole** [comment]
I had an issue like that before.  i just went into var's cache and wiped it all out and let it rebuild the database.  if it doesn't work, maybe others have a better solution but I would purge the whole thing except for the archlinux tarballs. just move them 2 files out of the arch directory. And after you purge everything.  mkdir arch and move those 2 files back in the arch directory and then run setupTermuxArch again.   Right now my sudo is shitting itself for not finding a shared library.  but that's code for you. lol

**Comment by raccoonsteven** [comment]
Try pacman-key  --init   then pacman-key --populate.
