### ISSUE TITLE
How can I use commands unique to termux?

### ISSUE THREAD

**Issue by ghost** [TermuxArch/TermuxArch#104]
As far as I searched, there is no commands that can execute termux-only commands, which are, for example, bound in termux-api package, without exiting TermuxArch. Is there any means to achieve this purpose?

I expected commands like the following:
```
# (assume that "clpfoo" is set on Android clipboard)
$ termux-eval "termux-clipboard-get"
clpfoo
$ termux-eval "termux-clipboard-set 'clpbar'"
$ termux-eval "termux-clipboard-get"
clpbar
```

(In fact, I want to use Android clipboard in (neo)vim. Because some plugins need Deno, which is unavailable on pure termux while available on TermuxArch, I have to run vim on TermuxArch)

**Comment by ghost** [comment]
I found a non-essential solution to this issue.

The following shellscript, which is in a termux environment,  receives command from TermuxArch via a text file.
(assuming existence of ~/storage/shared/temp/termux/cmd-from-arch.tmp)
```bash
#!/data/data/com.termux/files/usr/bin/bash

tmpdir=~/storage/shared/temp/termux 

if [ ! -f $tmpdir/.buf ]; then
  cat $tmpdir/cmd-from-arch.tmp > $tmpdir/.buf
  echo "" > $tmpdir/cmd-from-arch.tmp
  source $tmpdir/.buf 1> $tmpdir/cmd-rslt-to-arch.tmp
 2>&1
  rm -f $tmpdir/.buf
fi

```

and this crontab file executes above script in every 10 seconds

```crontab
* * * * * for i in `seq 0 10 59` ; do (sleep ${i}; ~/script/cmd-inter-to-arch.sh) & done;
```

then we can run commands like this in TermuxArch environment to use (and get output of) termux command:
```
# (assume that "clpfoo" is set on Android clipboard)
$ echo termux-clipboard-get > /storage/emulated/0/temp/termux/cmd-from-arch.tmp
$ sleep 10
$ cat /storage/emulated/0/temp/termux/cmd-rslt-to-arch.tmp
clpfoo
$ echo "termux-clipboard-set 'clpbar'" > /storage/emulated/0/temp/termux/cmd-from-arch.tmp
$ echo termux-clipboard-get > /storage/emulated/0/temp/termux/cmd-from-arch.tmp
$ sleep 10
$ cat /storage/emulated/0/temp/termux/cmd-rslt-to-arch.tmp
clpbar
```

However, I would like to emphasize that this is nonessential solution, so I wish to have such command I first mentioned.

**Comment by Young-Lord** [comment]
keep open
