### ISSUE TITLE
perl and its components broken

### ISSUE THREAD

**Issue by petkar** [TermuxArch/TermuxArch#13]
This is exclusive to this repository. I installed a fresh copy twice and tested it on both repos (this one and the /SDRausty/TermuxArch). Perl and many packages that depend on it like po4a and cpan are broken (binaries missing).
On [the other](https://github.com/SDRausty/TermuxArch) repo, it works perfectly fine, but on this repo it is failing. I'm not sure of the cause. Steps to reproduce : 
- clone [this](https://github.com/TermuxArch/TermuxArch) repo and install TermuxArch
- install `po4a` and `perl` (perl is optional since it's installed by default)
- try executing `po4a` or `cpan` and it returns error `bash: cpan: command not found`

Note that I already tried this with the stable repo too and these work normally. What commit do you think caused this regression?

**Comment by petkar** [comment]
Note that due to this step failing, `fakeroot-tcp` can't be installed either because `po4a` is one of its dependencies. And since the normal fakeroot doesn't work now (it used to, I'm not sure why it stopped, fakeroot-tcp has to be used), fakeroot-tcp is the only choice remaining and that too can't be installed because one of its dependencies is having an error.

**Comment by SDRausty** [comment]
> This is exclusive to this repository

Can you try this in both repositories please; Comment out lines [L127&&L128](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L127&&L128) in `knownconfigurations.bash`:
```
# printf "%s\\n" "$PROOTSTMNT"
# exit
```
Is there any difference in PROOTSTMNT?

**Comment by SDRausty** [comment]
> error `bash: cpan: command not found`

```
[user12:17~]$ cpan
Loading internal logger. Log::Log4perl recommended for better logging
Terminal does not support AddHistory.

To fix that, maybe try>  install Term::ReadLine::Perl


cpan shell -- CPAN exploration and modules installation (v2.27)
Enter 'h' for help.

cpan[1]>
```

```
[user12:20~]$ pcss | grep \\[installed | grep perl
core/perl 5.32.0-1 [installed]
extra/perl-error 0.17029-2 [installed]
extra/perl-mailtools 2.21-4 [installed]
extra/perl-timedate 2.33-2 [installed]
community/perl-yaml-tiny 1.73-4 [installed]
[user12:20~]$ pcss | grep \\[installed | grep po4a
community/po4a 0.59.1-2 [installed]
```

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/9d9c91d9cc24dfd74f1d1cf0d65d61afa0551bd3 commit adds `/etc/profile.d/perlbin.sh` support.  This enables the path for `po4a`.  The `pacman -Fl po4a` command helped answer this question.
