### ISSUE TITLE
Does it build successfully? Does the po4a binary exist?

### ISSUE THREAD

**Issue by SDRausty** [TermuxArch/TermuxArch#14]
- Refresh from the latest commit. Run `keys` as root. Restart termux and log in as user. Do `sudo pacman -Syu`
- Run `sudo pacman -Rncs fakeroot-tcp` if it exists (It used to build directly with `fakeroot` and patched `makepkg` but I wanted to retest building `fakeroot-tcp` using `fakeroot` which used to work earlier)
- Optionally run `sudo pacman -S fakeroot` `cd ~` `git clone https://aur.archlinux.org/yay.git` `cd yay && makepkg -si`. Check if it builds with `fakeroot`
- Run `cd ~ && git clone https://aur.archlinux.org/fakeroot-tcp.git && cd fakeroot-tcp && makepkg -si --noprepare`.
Does it build successfully? Does the po4a binary exist? I'm not sure if an update caused this or a regression due to a commit.

_Originally posted by @petkar in https://github.com/SDRausty/TermuxArch/issues/205#issuecomment-668238881_

**Comment by SDRausty** [comment]
> Check if it builds with fakeroot
 
`sudo pacman -S fakeroot ; cd ; git clone https://aur.archlinux.org/yay.git ; cd yay && makepkg -si`
```
==> Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
```
> Does it build successfully? Does the po4a binary exist? 

`cd && git clone https://aur.archlinux.org/fakeroot-tcp.git && cd fakeroot-tcp && makepkg -si --noprepare`
```
/home/user/fakeroot-tcp/PKGBUILD: line 41: po4a: command not found
==> ERROR: A failure occurred in build().
    Aborting...
[user22:51fakeroot-tcp]$ which po4a
which: no po4a in (/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/data/data/com.termux/files/home/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets)
[user22:52fakeroot-tcp]$ pcss po4a
community/po4a 0.59.1-2 [installed]
    Tools for helping translation of documentation
[user22:52fakeroot-tcp]$ uname -m
armv7l
```
After patching with `patch -n -i makepkg.diff -o makepkg /bin/makepkg` yay builds and installs:
```
[user23:59yay]$ yay --version
yay v10.0.3 - libalpm v12.0.2
```
However, po4a: command not found

**Comment by petkar** [comment]
Okay I tested the same, and makepkg seems to be able to enter the fakeroot environment with the normal fakeroot and build successfully after the patch. However perl components are still broken and the binaries still seem to be missing.
```
❯ whereis po4a
po4a: /usr/share/man/man7/po4a.7.gz /usr/share/man/man1/po4a.1p.gz

❯ whereis cpan
cpan: /usr/share/man/man1/cpan.1perl.gz
```
This isn't the case in the old repo and and the whereis command lists the path as `/usr/bin/po4a`. Which change do you think caused this regression?

**Comment by SDRausty** [comment]
> Does it build successfully? Does the po4a binary exist? 

This https://github.com/TermuxArch/TermuxArch/commit/9d9c91d9cc24dfd74f1d1cf0d65d61afa0551bd3 commit adds `/etc/profile.d/perlbin.sh` support.  This enables the path for `po4a`.  The `pacman -Fl po4a` command helped answer this question.  Now `fakeroot-tcp` builds as expected.  There are some errors when run.  I am not sure how important they are:

```
[user01:00fakeroot-tcp]$ fakeroot -v
fakeroot version 1.24
[user01:11fakeroot-tcp]$ fakeroot
dlsym(acl_get_fd): /usr/lib/libfakeroot/libfakeroot.so: undefined symbol: acl_get_fd
dlsym(acl_get_file): /usr/lib/libfakeroot/libfakeroot.so: undefined symbol: acl_get_file
dlsym(acl_set_fd): /usr/lib/libfakeroot/libfakeroot.so: undefined symbol: acl_set_fd
dlsym(acl_set_file): /usr/lib/libfakeroot/libfakeroot.so: undefined symbol: acl_set_file
[root@localhost fakeroot-tcp]#
```
The answer to both questions is yes.  Thank you for bringing these topics to my attention @petkar.

**Comment by petkar** [comment]
Amazing! Everything including makepkg, fakeroot, fakeroot-tcp and perl works as expected right off the bat now. Do you think the makepkg patch should be automated during installation by default?

**Comment by SDRausty** [comment]
> Do you think the makepkg patch should be automated during installation by default?

That would be nice, wouldn't it?  Maybe even extending it with `fakeroot-tcp` and `yay`...

**Comment by petkar** [comment]
> Maybe even extending it with fakeroot-tcp and yay...

That would indeed be nice. I think `yay` should be left optional to the user and shouldn't be enforced. As for fakeroot-tcp, it might be necessary if makepkg patch is installed.

> There are some errors when run. I am not sure how important they are:

These seem to be unimportant and can be ignored. The fakeroot-tcp repository provides the `silence-dlerror.patch` to hush these error message if they're annoying.

**Comment by petkar** [comment]
Another follow up question, how did yay succeed to build with the default `fakeroot` package if it can't correctly enter the fakeroot environment?

**Comment by petkar** [comment]
the prepare() part should apply the patch, but it fails with the error `patch: setting attribute security.selinux for security.selinux: Permission denied` and aborts the build. The workaround was to use `makepkg -si --noprepare` but that skips the patch which silences the errors which happen happens during preparation.

**Comment by petkar** [comment]
Okay I found a solution, edit the `PKGBUILD` file and in the prepare() function, append sudo to the patch command. Then simply running `makepkg -si` will correctly build it without errors and apply the patch successfully.

**Comment by SDRausty** [comment]
> Okay I found a solution,

Can you please try adding it to `_ADDpatchmakepkg_` and `_ADDmakeyay_` if you find the time;  Function `_ADDpatchmakepkg_` is also added to [archlinuxconfig.bash](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L499&&#L534) to help easily enable aur.

**Comment by petkar** [comment]
> Can you please try adding it to _ADDmakefakeroot-tcp_ and _ADDmakeyay_ if you find the time

Done! Submitted a pull request, check it out https://github.com/TermuxArch/TermuxArch/pull/16

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/7abd4f77d848ed74bd6eb5d31198d6c596ad2aa6 commit adds one command aur support via `makeyay.bash`.  If the prerequisite commands have not been run, `makeyay.bash` will execute them.  Thank you for helping to automate aur.
