### ISSUE TITLE
Chronic fakeroot issue with makpkg 

### ISSUE THREAD

**Issue by sobaee** [TermuxArch/TermuxArch#19]
Every time I try to install any tool e.g. "fakeroot-tcp"
I became depressed because of this 😢

It gives me this even after updating termuxarch and trying many solutions:

Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

Is there any solution yet?

**Comment by petkar** [comment]
Let me know if the following steps help : 

1. If you installed TermuxArch from this repository, simply do a refresh. If not run the following commands in termux : 
```
$ git clone https://github.com/TermuxArch/TermuxArch && cd TermuxArch
$ bash setupTermuxArch.sh re
```
   (Run full `refresh` if required)

2. Login as a user (which you created using `addauser`) with the command `startarch u <user>`

3. Execute the command `bash $HOME/bin/makefakeroot-tcp.bash`

**Comment by sobaee** [comment]
This picture contains what is the error I faced after successful cloning (git clone https://github.com/TermuxArch/TermuxArch && cd TermuxArch)

![Screenshot_20200813213243](https://user-images.githubusercontent.com/65910585/90173620-68780c00-ddad-11ea-91ef-9b0d25789bf9.jpg)

N.B: I did "rm -r /root/arch/tmp" and removed this folder but the same error continued.

**Comment by petkar** [comment]
I think you just attempted to install a TermuxArch proot instance inside a TermuxArch proot environment, hence the error. I'd recommend a fresh installation from termux, instead of cloning it inside the archlinux proot. If not, try the same refresh command after cloning the repository in the termux home (not TermuxArch)

**Comment by sobaee** [comment]
@petkar 
Okay, This is what I get in Termux itself:
![Screenshot_20200813215557](https://user-images.githubusercontent.com/65910585/90175282-dcb3af00-ddaf-11ea-8f61-45e67205a5a3.jpg)

**Comment by petkar** [comment]
Try `rm -rf TermuxArch` and then the same command.

**Comment by sobaee** [comment]
@petkar 
![Screenshot_20200813215904](https://user-images.githubusercontent.com/65910585/90175554-45029080-ddb0-11ea-874c-f446c6975496.jpg)

**Comment by petkar** [comment]
I'm not aware of why the directory isn't being removed due to lack of information but you could just cd into it and run `git pull` to update it and proceed with the refresh.

**Comment by sobaee** [comment]
@petkar 
Okay
It asked me define what I want to "pull", this is the result

**Comment by sobaee** [comment]
@petkar 
I used these commands in Termux itself  and sucessfully updated TermuxArch

chmod 777 TermuxArch
Then rm -rf TermuxArch
Then git clone https://github.com/TermuxArch/TermuxArch && cd TermuxArch
Then bash setupTermuxArch.sh re

Many thanks

**Comment by sobaee** [comment]
@petkar 
Now about the new issue:

![Screenshot_20200813222209](https://user-images.githubusercontent.com/65910585/90177604-76309000-ddb3-11ea-9d4f-49d8dfecb9d1.jpg)

I can add users in TermuxArch by other methods like "sudo useradd -m", but you and @SDRausty always advice on creating the user using "addauser" command

**Comment by petkar** [comment]
I'm not sure of the version of the local clone. For all sanity purpose try `cd && mkdir git-repo && cd git-repo && git clone https://github.com/TermuxArch/TermuxArch && cd TermuxArch && bash setupTermuxArch.sh refresh`

**Comment by petkar** [comment]
> but you and @SDRausty always advice on creating the user using "addauser" command

The addauser command is a script that uses useradd and also performs additional configurations like copying profile information and local binaries and scripts that may be usefu one of which is the makefakeroot-tcp.bash.

**Comment by sobaee** [comment]
> I'm not sure of the version of the local clone. For all sanity purpose try `cd ~ && mkdir git-repo && cd git-repo && git clone https://github.com/TermuxArch/TermuxArch && cd TermuxArch && bash setupTermuxArch.sh refresh`. This must be executed in termux of course.


Should I try to full refresh TermuxArch to use "addauser" command?
Now I already have the latest TermuxArch (2.0.229).

Is there anyway to be able to use "addauser" command wothout full refresh?

**Comment by petkar** [comment]
> Should I try to full refresh TermuxArch to use "addauser" command?

This is not necessary if you have refreshed to the latest version. Simply run `startarch` to enter the proot. Executing `addauser user` inside the root ArchLinux proot. Setting up `passwd user` and installing `sudo` beforehand is recommended.

**Comment by sobaee** [comment]
@petkar 
TermuxArch is not recognize this command (addauser) at all:
![Screenshot_20200813224054](https://user-images.githubusercontent.com/65910585/90179559-49ca4300-ddb6-11ea-8142-9481b9ef42fd.jpg)

**Comment by petkar** [comment]
Does the `bin` folder exist in the root directory? Is the `.profile` and `.bash_profile` sourced? If not, you might have to run `refresh` and `re` again.

**Comment by sobaee** [comment]
> Executing addauser user inside the ArchLinux proot

After googling this, I think there is something called "Archlinux proot" which I have to set it up before I can use "addauser" command.

By using this after cloning TermuxArch again:
bash setupTermuxArch.sh re ar

Am I right?

**Comment by sobaee** [comment]
> Does the `bin` folder exist in the root directory? Is the `.profile` and `.bash_profile` sourced? If not, you might have to run `refresh` and `re` again.

How do I know they are out there or not?

Iam a beginner, thank you for your patience.

**Comment by petkar** [comment]
> How do I know they are out there or not?

`ls -la /root` should list all the files (including hidden) that exist in the home directory of the root user.

**Comment by sobaee** [comment]
> > How do I know they are out there or not?
> 
> `ls -la /root` should list all the files (including hidden) that exist in the home directory of the root user.

Then yes I have bin folder and those two files in /root directory.

**Comment by petkar** [comment]
Not sure why it isn't in path. Maybe something got messed. A refresh should fix it. However you can directly execute it by calling its full path like `/root/bin/addauser username` inside the Linux environment with the root user account.

**Comment by sobaee** [comment]
@petkar @SDRausty 
I Successfully created a user by addauser and ran this:
bash $HOME/bin/makefakeroot-tcp.bash

Then got this:
![Screenshot_20200814002340](https://user-images.githubusercontent.com/65910585/90188606-6ff6df80-ddc4-11ea-81fe-fdb135e88101.jpg)

N.B: I didn't think that '/bin/makepkg' has been updated, I think this error because I updated '/bin/makepkg' from makepkg.zip file @SDRausty  posted here:
https://github.com/SDRausty/TermuxArch/issues/38#issuecomment-660607270
Why the refresh process of TermuxArch doesn't contain this file?

I got this

**Comment by sobaee** [comment]
Yaaaaaaaaaaah 🥳🥳🥳🥳🥳

Successfully installed fakeroot-tcp after spending 2 weeks trying to do it.

The problem was that refershment of TermuxArch copy /bin files to an old user which I created in wrong way (not by addauser)
What I did after referhment and login with my username (by startarch u username), that I run this:
cp /root/bin/* /bin
Which copied the updated files to my correct username, then I ran this:
bash $HOME/bin/makefakeroot-tcp.bash

And everything done and success.

All thank to @petkar and on the first place to @SDRausty.

**Comment by SDRausty** [comment]
> All thank to @petkar and on the first place to @SDRausty.

You are welcome; Many people have contributed to help this project to work as desired on device.   You might be surprised @sobaee.  You are a contributor to the project now too.  Thank you!
