### ISSUE TITLE
TeXworks not saving conf in proot, migrated from Termux issues

### ISSUE THREAD

**Issue by cargocultprog** [TermuxArch/TermuxArch#20]
Using Arch Linux ARM in proot, device not rooted. Android 9, Samsung Galaxy Tab A (WiFi, no phone). LXDE GUI. Works very well.

TeXworks functions correctly, with exception: It can read, but not write or modify, its configuration file at `~/.config/TUG/TeXworks.conf`

Possibly also applies to other things in .config.

I contacted the TeXworks developer. No problem seen on ordinary Linux. Also tried building source code in Arch proot. It builds and works, but with same exception.

No error messages anywhere.

GUESS: May have something to do with interaction beteen proot and qt5. The .conf file uses qt5 methods for write. Unfortunately, I am not enough of a programmer to know.

If due to proot qt5, then the issue may affect other programs using qt5.

**Comment by cargocultprog** [comment]
Hi -

Got the invitation to join TermuxArch, but Imust decline it. I do not know how to program (only simply BASH scripts), and I do not have the Android SDK. Thanks, anyway.

**Comment by SDRausty** [comment]
> can read, but not write or modify, its configuration file at `~/.config/TUG/TeXworks.conf`.

> [`chown: changing ownership of '/home/xd003/.cache/yay/heroku-cli/pkg/heroku-cli/usr/lib/node_modules/heroku/node_modules/treeify/examples/eukaryotes.js': Operation not permitted          
chown`](https://github.com/TermuxArch/TermuxArch/issues/22#issue-686428848)

> The way permissions are configured has been [revised](https://github.com/TermuxArch/TermuxArch/commit/f7ae13a450e939364b23d0c18061350180b2a9a6);  Hopefully this change will have a positive effect on our devices and `heroku-cli` will build for you as expected.  

In this issues case this revision concerns `TeXworks`.  The underlying cause of both these issues might be the same, file and directory permissions.  File and directory permissions are revised.  @cargocultprog can you check if TeXworks runs is expected with this new change please?

Executing `setupTermuxArch re` should be enough to update this change on your device.  The command `setupTermuxArch h[elp]` has more information about 
 system refresh options.

**Comment by cargocultprog** [comment]
I use only the Arch version, not the yay build, so I cannot advise.

**Comment by SDRausty** [comment]
> use only the Arch version

My last question was not about building `TeXworks` with a`yay`.   Please let me elaborate so I will be a little clearer.

> File and directory permissions are revised. 

> Executing `setupTermuxArch re` should be enough to update this change on your device. 

> TeXworks functions correctly, with exception: It can read, but not write or modify, its configuration file at ~/.config/TUG/TeXworks.conf

Does this new change in the file and directory permissions  scheme have an effect on the file that we are discussing?

**Comment by SDRausty** [comment]
> Numerous iterations, and at that nuance iterations requiring time consuming testing have given positive results.   This [commit](https://github.com/SDRausty/TermuxArch/commit/75fad3357d63c2ea12468eb0c06223090192fd73) and the  preceding few have helped to make script `makefakeroottcp` and more importantly script `makeyay` functional again once more.

From https://github.com/SDRausty/TermuxArch/commit/75fad3357d63c2ea12468eb0c06223090192fd73, this has rewritten permissions through the PRoot init statement for the user accounts. 

This means that the file you referenced that did not work might possibly work  correctly in the PRoot environment on Android now!  If you missed the updates in the last couple of days @cargocultprog, the simple `setupTermuxArch re` should update your system correctly.  

Creating a new user account after refreshing to test TeXwork is advised as file permissions at creation is affected.   If you are installing a new system, creating a new user account is unnecessary as a default user account with the name `user` will be created for you.

This is a subtle change which yields radical results for the better as far as I can tell.  There have also been other subtle changes that fix permissions in the last week, a reinstallation of the system might be justified to fully test new changes.  Please remember to backup your data from your user accounts before reinstalling.

**Comment by cargocultprog** [comment]
In my case, not a permissions issue. I installed via my own script, and have full permissions. The problem sems to be have something to do with qt5, which does have some issues in proot and Termux. But this issue should be dropped. The user base is very small, and the configuraion file is easily edited manually. I do not have enough device space to do a test reinstall.

**Comment by SDRausty** [comment]
@cargocultprog thank you for replying so quickly.  

>  I installed via my own script, and have full permissions. 

Would you be apt to share this script at this website please?
https://github.com/TermuxArch/scripts.TermuxArch/pulls
The process is almost as simple as opening an issue:
a) Fork Repository
b) Make changes, in this case, an addition, a new file
c) Create PR
> I do not have enough device space to do a test reinstall.

Enough device space makes me think of this issue:
> https://github.com/TermuxArch/TermuxArch/issues/3 Can PRoot be used to access a Linux distribution from external storage such as an SD card?

Possibly, this topic should be revisited. Do you have room in external SD card storage?

**Comment by cargocultprog** [comment]
No, my method is not a modification of termuxArch. It is entirely different. A pull request cannot help. I only mentioned it here, because I thought it might affect your script. It is best to drop the issue. I may be the only person in the world using texworks on Android proot.

As for an SDcard, it would have to be formatted ext4 (or similar) for POSIX file permissions. Even then, it might not work. Most users cannot format to ext4, because Android will not allow it except for rooters. Not everyone has access to a desktop Linux or Mac machine (I do not).
