### ISSUE TITLE
TermuxArch after Android 10 changes

### ISSUE THREAD

**Issue by mukhtharcm** [TermuxArch/TermuxArch#23]
I have a simple question.
Will TermuxArch still work after the changes that will occur after termux changes to android 10?

**Comment by SDRausty** [comment]
@mukhtharcm thanks for asking an important question;  Can you please find answers to these questions too?  

1) Will BASH scripts still work after the update coming in November?  Hopefully yes they will.

2) What will shell scripts be able to do?   What will their capabilities be?


Please reach out and post your findings here if you can.

**Comment by SDRausty** [comment]
> after the changes that will occur after Termux changes to android 10

One solution is not to update the system once it is accomplishing the given tasks.

**Comment by BL4CKH47H4CK3R** [comment]
Currently working with Ubuntu Touch (halium) & PostMarketOS + Plasma port on android.
I will surely check this issue quickly
What about Arch on (LinuxDeploy + JuiceSSH/Other SSH client) ? 
- Anyone tried ?

**Comment by SDRausty** [comment]
https://github.com/termux/termux-packages/wiki/Termux-and-Android-10

https://www.reddit.com/r/termux/comments/injx54/question_about_upcoming_android_10sdk29_changes/

https://www.reddit.com/r/termux/comments/ini0bp/proot_after_the_great_android_10_changes/

> Does it mean that I can use TermuxArch after the migration?

> Yes, you should read this issue, it will solve ur all confusions/queries . https://github.com/termux/termux-app/issues/1072
