### ISSUE TITLE
sudoers file is apparently absent in the latest TermuxArch v2.0.519

### ISSUE THREAD

**Issue by xd003** [TermuxArch/TermuxArch#24]
I just updated TermuxArch an hour ago to latest TermuxArch  v2.0.519 ( at the time of opening this issue )
After installation got completed , i tried to add my user but it returned an error saying ```/etc/sudoers``` file is absent.
I checked it using file manager too and indeed it was absent . This issue didn't existed 2 days back , i think something changed very recently could have caused it . Probably you can fix this thing pretty quickly as its a minor issue.

Here's the whole error
```
[root20:05bin]$ ./addauser xd003                             
Adding Arch Linux in Termux PRoot user 'xd003' and creating Arch Linux in Termux PRoot user xd003's home directory in /home/xd003...
sed: can't read /etc/sudoers: No such file or directory
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
      --debug
                 annotate program execution
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  --follow-symlinks
                 follow symlinks when processing in place
  -i[SUFFIX], --in-place[=SUFFIX]
                 edit files in place (makes backup if SUFFIX supplied)
  -l N, --line-length=N
                 specify the desired line-wrap length for the `l' command
  --posix
                 disable all GNU extensions.
  -E, -r, --regexp-extended
                 use extended regular expressions in the script
                 (for portability use POSIX -E).
  -s, --separate
                 consider files as separate rather than as a single,
                 continuous long stream.
      --sandbox
                 operate in sandbox mode (disable e/r/w commands).
  -u, --unbuffered
                 load minimal amounts of data from the input files and flush
                 the output buffers more often
  -z, --null-data
                 separate lines by NUL characters
      --help     display this help and exit
      --version  output version information and exit

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All
remaining arguments are names of input files; if no input files are
specified, then the standard input is read.

GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.

 TermuxArch WARNING:  Generated script signal 2 near or at line number 63 by !

addauser  2.0.519 [Exit Signal 201]: DONE  🏁
```

**Comment by SDRausty** [comment]
> [root14:07~]$ addauser a                                                      Adding Arch Linux in Termux PRoot user 'a' and creating Arch Linux in Termux PRoot user a's home directory in /home/a...
passwd: password expiry information changed.                                  Added Arch Linux in Termux PRoot user 'a' and configured user 'a' for use with the Arch Linux command 'sudo'.  Created Arch Linux user a's home directory in /home/a.  To use this account run 'startarch login a' from the shell in Termux.  To add user accounts you can use 'addauser a' in Arch Linux and 'startarch c[ommand] addauser a' in the default Termux shell.  Please remember not to nest proot in proot unknowingly by using 'startarch' in 'startarch' as this is known to cause issues for PRoot users.
addauser  2.0.519: DONE 🏁

This might sound surprising to you @xd003, I encountered a similar message  hoursc ago.  You could say the exact same error in one of the updates hours ago.  As far as I can tell, this is resolved. Do do you agree?

**Comment by SDRausty** [comment]
Try refresh.  If not then please try reinstall and see if the error persists. Refreshing the system should suffice.  

I just checked between the last message and now: two successful outcomes as root user with the same version number and one more successful with sudo v2.0.518 in a user account.

**Comment by SDRausty** [comment]
This message that showed on our screens at approximately the same time has been gone for hours.  Two new fresh v2.0.519 installations are attempting into `makeyay`...


Do you have any insight into this issue @xd003, as I cannot explain it?

**Comment by xd003** [comment]
> Try refresh.  If not then please try reinstall and see if the error persists. Refreshing the system should suffice.  
> 
> I just checked between the last message and now: two successful outcomes as root user with the same version number and one more successful with sudo v2.0.518 in a user account.

Yes you are correct 
I just ran ./setupTermuxArch refresh and it has resolved that issue .Now sudoers file is present,  pretty weird why it had happened earlier . To properly get the hold of such anomalies , i think if TermuxArch saves the debug output of the bash installation in a separate file , it could help to analyse if something went wrong later

**Comment by SDRausty** [comment]
This commit might have anomalies as well.  The jump in the version number is explainable because their updates to the repository but not the script.  When I search the web page for CHANGE, how would you explain that the checksum changed, but the file `CHANGE.log`  does not appear to have changed in about a month?

> the debug output of the bash installation in a separate file ( probably in /var/backups/arch), it could help to analyse if something 

This is a very interesting idea @xd003!  Can you outline how you would go about implementing a setup.log file?

**Comment by SDRausty** [comment]
> Two new fresh v2.0.519 installations are attempting into makeyay...

Both made `yay` correctly.  On one device there was a little free space left, and `yay heroku-cli` built as expected.

**Comment by SDRausty** [comment]
@JanuszChmiel just opened issue [setuptermuxarch script causes error #69](https://github.com/SDRausty/termux-archlinux/issues/69).  I think this commit https://github.com/TermuxArch/TermuxArch/commit/812435de8338cfeaa56bd15d65ef05b7f656aa58#diff-147d3dac5c5d3cacbd74a5925f7ef3cfL646  kind of illustrates what we are dealing with here @xd003 as far as  anomalies are concerned.  Please notice this modification only includes brackets: `STIME="$(SDATE)`

**Comment by SDRausty** [comment]
@JanuszChmiel just opened issue [setuptermuxarch script causes error #69](https://github.com/SDRausty/termux-archlinux/issues/69).  This commit https://github.com/TermuxArch/TermuxArch/commit/812435de8338cfeaa56bd15d65ef05b7f656aa58 kind of illustrates what we are dealing with here @xd003 as far as finding anomalies while using smartphones is concerned.  

Please notice [this modification only includes the  brackets](https://github.com/TermuxArch/TermuxArch/commit/812435de8338cfeaa56bd15d65ef05b7f656aa58#diff-147d3dac5c5d3cacbd74a5925f7ef3cfL646) in  `STIME="$(SDATE)` which should be `STIME="$SDATE`, and the relevant file changes.  Have you noticed any similar anomalies in your work?

**Comment by SDRausty** [comment]
> fortunately to be found and usually quickly corrected, sometimes not, @xd003 and I are discussing an error which magically appeared the night before, then apparently disappeared by itself at this TermuxArch/TermuxArch#24 issue.

@JanuszChmiel thank you once more for sharing news about this error so quickly.  I was thinking about this anomaly and the one mentioned in issue 24 and its impact on the user base.   

To sum up, this error that you found @JanuszChmiel potentially impacted a lot of users, many users and could have remained undetected for quite some time. The reason being is that the effects of this error affects older model devices and/or older Android applications.  And as far as we know the unsupported post Android 5 user base is enormous.  

Reprint from https://github.com/SDRausty/termux-archlinux/issues/69  

In view of this new event, I am really really glad that you @xd003 had opened this issue.  Thank you again 🎵 🎶

**Comment by SDRausty** [comment]
I do not really want to be wasting your time @xd003, and even though this https://github.com/SDRausty/termux-archlinux/commit/3e05493b8da82e9cde5971d56162be225dfa8eee commit is not at this repository it does affect this project.  Can you compare commits https://github.com/TermuxArch/TermuxArch/commit/1f0ee1e9d810f8bae4c218455cad4cc36c8e4292 and commit https://github.com/SDRausty/termux-archlinux/commit/3e05493b8da82e9cde5971d56162be225dfa8eee?  

Technically these commit should be identical even though they are on different machines, and summarize the differences between them when you have some spare time, please?

**Comment by SDRausty** [comment]
The reason I'm bringing this up his I do not quite understand what's happening from this point here:
`92c117b5330f2f0ef669c3dd31263dbd5c7fcb944b0d744e7d5e58b5f5ba555ce23f36682fd7c1afe4dbe3e32a4d1d46bb9ce86375bf042d9e17746e020fef02  ./setupTermuxArch`
https://github.com/SDRausty/termux-archlinux/commit/3e05493b8da82e9cde5971d56162be225dfa8eee#diff-826f218ca0ba636cf35958f862d3fc96R3

The question, it should be simple. Why are some checksums rewritten when there is no apparent change?

**Comment by SDRausty** [comment]
I had decided to do something that is not usually done as far as I know.  I decided to dedicate two machines to installing new installs of Arch Linux in Termux PRoot in each one.  The result is success, including building `yay` with command `makeyay` x3.  On one of these smartphones I decided to install concurrent installations see how this feature works again.

Of the three successful installs @xd003, there were more than three attempts. An unsuccessful attempt ran into the same message that this issue is primarily about, and I took a very very close look at possible similar signals that preceded this one:
> /etc/sudoers: No such file or directory

And there were some. It appears that somehow the data connection had prevented the `sudo` package install.  No data connection can bring about this result. Do you think that this is possible in your case?

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/10db9b36bf99dd061635eed0c40ee9f7912fa54b add support support for `sudoers` file absence.
