### ISSUE TITLE
Implementing QEMU

### ISSUE THREAD

**Issue by SDRausty** [TermuxArch/TermuxArch#25]
EDIT: This command `setupTermuxArch q[emu] [customdir]` supersedes the struck out notes below.  The command `setupTermuxArch h[elp]` provides help information.

~~QEMU has along with other features been implemented for years.  Unfortunately, it is still under documented and still awaiting full implementation.  There are two implied references to QEMU in the help; `setupTermuxArch h`:~~

~~>[./path/systemimage.tar.gz [customdir]]  Install directory argument is optional.  Network install can be substituted by copying systemimage.tar.gz and systemimage.tar.gz.md5 files with 'setupTermuxArch ./[path/]systemimage.tar.gz' and 'setupTermuxArch /absolutepath/systemimage.tar.gz'.~~    
~~> [systemimage.tar.gz [customdir]]  Install directory argument is optional.  Network install can be substituted by copying systemimage.tar.gz and systemimage.tar.gz.md5 files with 'setupTermuxArch systemimage.tar.gz'.`~~

~~The next steps should be obvious:~~
~~1) find system image of desired architecture,~~
~~2) download image,~~
~~3) use one of the copy image commands.~~

~~These next steps might not be so obvious to all. 
 Especially the newcomer,~~ what is [QEMU](https://www.qemu.org/)?

> QEMU is a generic and open source machine emulator and virtualizer.

What does that mean might be a question? Don't worry read on.  The answer is obvious.  Install QEMU in Termux to activate this feature:

```
[u0_a9112:01TermuxArch]$ pkg list-available |f qemu                                                                                                         
WARNING: apt does not have a stable CLI interface. 
Use with caution in scripts.                                                                                                                                                           
933:qemu-common/stable 1:4.2.1 arm                                            
934:qemu-system-aarch64-headless/stable 1:4.2.1 arm
935:qemu-system-arm-headless/stable 1:4.2.1 arm
936:qemu-system-i386-headless/stable 1:4.2.1 arm                              
937:qemu-system-riscv32-headless/stable 1:4.2.1 arm
938:qemu-system-riscv64-headless/stable 1:4.2.1 arm                           
939:qemu-system-x86_64-headless/stable 1:4.2.1 arm                            
940:qemu-user-aarch64/stable 1:4.2.1 arm                                      
941:qemu-user-arm/stable 1:4.2.1 arm
942:qemu-user-i386/stable 1:4.2.1 arm                                        
943:qemu-user-riscv32/stable 1:4.2.1 arm                                      
944:qemu-user-riscv64/stable 1:4.2.1 arm                                      
945:qemu-user-x86_64/stable 1:4.2.1 arm
946:qemu-utils/stable 1:4.2.1 arm
```

You can also attempt to build these `qemu` packages with the `yay` command.  The last step might seem confusing.  I think it is because the step is overly simple.  

```
$ wc -l ~/arch/var/binds/fbindexample.prs
11
$ cat ~/arch/var/binds/fbindexample.prs
```

~~So I will not waste space here other than to say that using command `setupTermuxArch re` after reading file  (wc -w 128) `fbindexample.prs` should~~ open up any architecture you choose to install in your smartphone, smatTV, tablet and wearable.  Once this issue is resolved the TermuxArch end user will not even know about this step, unless they chose to explore the TermuxArch code.

I would also like to add that **command `setupTermuxArch b` can help with more than just with this issue** here:
```
j=0 ; for i in $(wc -l ~/TermuxArchBloom/*|cut -d"/" -f 1|head -n 11);do j="$(($i + $j))" ; done ; echo $j ; unset i j
5330
j=0;for i in $(wc -w ~/TermuxArchBloom/*|cut -d"/" -f 1|head -n 11);do j="$(($i + $j))";done;echo $j ;unset i j
31341
```

This is the entire data set presented for your review.  One tap [QEMU](https://www.qemu.org/) is still a couple of steps away as of today.  Comments regarding the data set are welcome here, especially how to implement one tap option QEMU easily.  The goal of the data set is more robustness with fewer lines if possible.  Human legibility of the code is paramount, along with execution speed and the end user experience.

**Comment by SDRausty** [comment]
If your target install system is aarch64/arm64 then this line of code [`CPUABI="$(getprop ro.product.cpu.abi)"`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch#L653) should be changed to `CPUABI="arm64-v8a"`.

[Lines 596 through 600 in file `setupTermuxArch`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch#L596&&#L600) have more information about how to manually choose the correct architecture  for this planned implementation of the **QEMU automatation** which is still currently an absent option:

`# Used for development;  The command 'getprop ro.product.cpu.abi' can be used to ascertain the device architecture.  Matching an alternate CPUABI* will install an alternate architecture on device.  The original device architecture must be changed to something else so it does not match.  This is usefull with QEMU to install alternate architectures on device.`
```
declare CPUABI5="armeabi"	# Used for development;  The command 'getprop ro.product.cpu.abi' can be used to ascertain the device architecture.  Matching an alternate CPUABI* will install an alternate architecture on device.  The original device architecture must be changed to something else so it does not match.  This is usefull with QEMU to install alternate architectures on device.
declare CPUABI7="armeabi-v7a"	# used for development
declare CPUABI8="arm64-v8a"	# used for development
declare CPUABIX86="x86"		# used for development
declare CPUABIX86_64="x86_64"	# used for development
```

**Comment by SDRausty** [comment]
`$ f ro.product.cpu.abi setupTermuxArch`

`634:CPUABI="$(getprop ro.product.cpu.abi)" && SYSVER="$(getprop ro.build.version.release)" && NASVER="$(getprop net.bt.name ) $SYSVER" || _PSGI1ESTRING_ "CPUABI setupTermuxArch ${0##*/}"`

Change `ro.product.cpu.abi` to one of the five architectures that are mentioned above.

**Comment by JanuszChmiel** [comment]
Mr Rausty,

I would like to warn you for very important Qemu issue. It is speed of The executed code. Because Android devices can not be rooted simply. As A result, normal user have no chance to patch his used Android kernel with Kqemu kernel module. Because to be honet, Qemu which execute complex code is only usable if it is accelerated with Kqemu kernel module. As A result, Fedora support wonderful virt-manager which uses Qemu in conjunction with Kqemu. There is even An attempt to allow users of Termux to boot whole Linux distro no in userspace mode as Proot technique allows. 
https://github.com/xeffyr/alpine-term

It is even possible to run various Linux distros by using this technique. But The execution speed is very slow even on Octa core CPUS with ANdroid 8.0 and with 4 GB of RAM.

Proot still offer The best execution speed when comparing with Qemu which do not use Kqemu kernel module for its accelerated running. Kqemu requires hardware virtualisation to be available on A ARM CPU. The question is, if cheap ARM cpus even contain hardware virtualisation when CPU is being manufactured in The factory.

I have tried Alpine with Termux which run by using Qemu. It runs, but because Qemu emulates CPu hardware, it cost many penalties.

Yours idea is goodly thinked, but speed wwill be very probably The limitation factor.

**Comment by SDRausty** [comment]
> speed will be very probably the limitation factor.

I cannot but agree from what I know of this subject of QEMU. However there is even a bitter bigger limiting factor than the one we are dwelling on here!  This is being able to install an alternate architecture in a smartphone  easily with only one tap!  Do you agree with this point of view?

**Comment by SDRausty** [comment]
Simply by opening this topic the goal is much closer, and should be easier to obtain.  Do you agree?

> speed will be very probably the limitation factor.

I cannot but agree from what I know of the subject of QEMU. However there is even a bitter bigger limiting factor than the one we are dwelling on here right now!  This is being able to install an alternate architecture in a smartphone  easily with one tap only!  Do you agree with this point of view @JanuszChmiel?

**Comment by SDRausty** [comment]
> regarding the data set:

Option `setupTermuxArch o` displays part of the data set in present. May I get a little help with this please?

I do not want to delete it because it can be a good entry point for the code phobic future coder.  What option should this presentation receive; `setupTermuxArch option` can be expanded into a full data set presentation in Matrix format in the cli screen:

![Screenshot_20200908-203250](https://user-images.githubusercontent.com/27742457/92540409-7d13bc80-f212-11ea-8bf6-a6d49b23b73c.png)

@JanuszChmiel thank you for coming up with a very nice name for the Orca project we are working on for long months now.  The name `orcaconfig` is a good name for the user wants to do.  

**Name suggestions for the TermuxArch Matrix option are requested.**  The `o` option should remain open for future development...

**Comment by JanuszChmiel** [comment]
Yes I fully agree with you in this point of wiev.
The next true is that if Qemu is being used not to boot whole Linux distro
with whole kernel, that there is not too much instructions to execute and
Qemu can be good alternative.

**Comment by JanuszChmiel** [comment]
I had a big dream. Run Wine for X86 on Aarch64 platform and run my favourite
audio games for visually impaired by using Linux on Android device by using
Proot.
Unfortunately, The most .exe apps have been compiled for X86 or for X64.
There is no free simple converter, which could simply convert machine code
from one platform to another.
Play those games on A phone instead of a standard IBM/PC compatible machine
would be very exciting idea. BUt I know, that Qemu would be very probably
too slow to allow this.
The next important question is, if build Wine pulseaudio sound support would
be compatible with used approach, that TCP protocol is being used to stream
sound packets to Pulseaudio server which run in Termux not on a real Linux
distro such as Arch Linux.
But it would be very interesting experiment.

**Comment by SDRausty** [comment]
> run my favourite audio games for visually impaired

Can you share with us please what these games are?  Are they available at GitHub?

**Comment by JanuszChmiel** [comment]
I love one really unique audio games for visually impaired. Its name is
topspeed. It is written by using Visual C++.
It uses 3d sound to simulate real car race. You can hear cars around you,
when you want to run fater than The car infront of you, you can hear The
sound of The slower car. User must turn right, left, Cars can run to various
ways.
The source on Github is here.
https://github.com/PlayingintheDark/TopSpeed
But I must warn you that simply recoding this complex C source to be
compatible with Linux compiler will not be easily possible.
I love also other game, which is compiled by using special game engine for
audio games development. It require X86 environment and Wine emulator.
Topspeed also require WIndows emulator.
 
I AM afraid, that Wine will not support to use Topspeed, since it uses many
dlls from Microsoft corporation which is copyright problem. Microsoft
directX to generate sound, and Microsoft Visual C++ redistributable.
 
Here is other excellent audio game for us. It is Tube simulator from London.
 
http://www.ndadamson.com/get-tubesim-portable.php

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/7eb1440dd1a6da3ee343ca3034de53abeee982ce commit adds basic QEMU support for TermuxArch.  To access this new future you can use this command `setupTermuxArch q`.  The command `setupTermuxArch h` has more information.

This command still does not support installing QEMU which must be done manually.  If installing x86_64 on a 64-bit arm smartphone, this is a recommended QEMU package configuration:
```
qemu-user-x86_64/stable,now 1:4.2.1 aarch64 [installed]
```

```
$ pkg list-a|f qemu                                               
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.  
936:qemu-common/stable 1:4.2.1 aarch64                                           
937:qemu-system-aarch64-headless/stable 1:4.2.1 aarch64
938:qemu-system-arm-headless/stable 1:4.2.1 aarch64                              
939:qemu-system-i386-headless/stable 1:4.2.1 aarch64
940:qemu-system-riscv32-headless/stable 1:4.2.1 aarch64
941:qemu-system-riscv64-headless/stable 1:4.2.1 aarch64
942:qemu-system-x86_64-headless/stable 1:4.2.1 aarch64
943:qemu-user-aarch64/stable 1:4.2.1 aarch64
944:qemu-user-arm/stable 1:4.2.1 aarch64
945:qemu-user-i386/stable 1:4.2.1 aarch64                                        
946:qemu-user-riscv32/stable 1:4.2.1 aarch64                                     
947:qemu-user-riscv64/stable 1:4.2.1 aarch64                                     
948:qemu-user-x86_64/stable,now 1:4.2.1 aarch64 [installed]                      
949:qemu-utils/stable 1:4.2.1 aarch64
```

**Comment by SDRausty** [comment]
To use this new feature which is currently being developed effectively:
1) install qemu for the target architecture,
2) choose option `setupTermuxArch q[emu] [customdir]`,
3) create a qemu bind in directory `/var/binds/`.  File `/var/binds/fbindexample.prs` has more information.

**Comment by JanuszChmiel** [comment]
Oh. And will be possible to run some X86 apps while working with AARch64
CPU?
It would be excellent.

**Comment by SDRausty** [comment]
> It would be excellent.

It appears that this issue is down to three simpler steps now.  This is still a long way away from a one tap any architecture chosen install;  And I am glad to see that this issue is making some headway.

**Comment by SDRausty** [comment]
> possible to run some X86 apps while working with aarch64

This error `/usr/bin/env: Invalid ELF image for this architecture` happens on aarch64 when x86 is chosen:
```
Setting mode to qemu.  This feature is being developed.
Please install one of the qemu tools from this list in a new session if not already installed before continuing:
qemu-user-aarch64/stable 1:4.2.1 aarch64
qemu-user-arm/stable 1:4.2.1 aarch64
qemu-user-i386/stable,now 1:4.2.1 aarch64 [installed]
qemu-user-riscv32/stable 1:4.2.1 aarch64
qemu-user-riscv64/stable 1:4.2.1 aarch64
qemu-user-x86_64/stable,now 1:4.2.1 aarch64 [installed]
Please select the architecture by number from this list:
1) armeabi
2) armeabi-v7a
3) arm64-v8a
4) x86
5) x86_64
```

**Comment by SDRausty** [comment]
> possible to run some X86 apps while working with aarch64

It appears like it is possible to achieve this goal since this https://github.com/TermuxArch/TermuxArch/commit/77751cbcdb03dd475ae6bacc3763a4b178f4aa79.  The command `./setupTermuxArch qemu install i386` will attempt to install and configure an x86 installation in an `~/i386` alternate directory after choosing option `4) x86` @JanuszChmiel.  There are still a few rough edges in the configuration sections which deserve a little honing.

**Comment by SDRausty** [comment]
> speed will be very probably The limitation factor.

Speed can be benchmarked with [this script](https://github.com/TermuxArch/scripts.TermuxArch/blob/master/frags/stdoutbench.sh).  The current limiting factor is the different configurations which the different architectures have @JanuszChmiel.  Have you had any success with alternate architectures on your smartphone?

**Notes about reinstalling for testing**, this command `setupTermuxArch i customdir` can be called to assist in the task of testing the install process:

`[i[nstall] [customdir]]  Install Arch Linux in a custom directory.  Instructions: Install in userspace.  The HOME directory is appended to the installation directory.  To install Arch Linux in HOME/customdir use 'bash setupTermuxArch install customdir'.  In the BASH shell you can use './setupTermuxArch install customdir'.  All options can be abbreviated to one, two and three letters.  Hence './setupTermuxArch install customdir' can be run as 'setupTermuxArch i customdir' in BASH.`

The newly implemented command `setupTermuxArch q i customdir` can also be summond to help resolve this issue:

`[q[emu] [customdir]]  Partial Implementation:  Install alternate architecture on smartphone with QEMU.`

The command `setupTermuxArch h` has more  information.  If space is not an issue on smartphone it may be possible to **run all the concurrent architectures for testing this issue**.

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/c1b1e83a136768bb83c9b8f471a16849fb6d58f0 commit automates installing the user selected QEMU component and closes this issue.  Should there be individual architecture issues regarding this QEMU implementation, please open a new issue specifying the architectures used, and the exact nature of the issue.

**Comment by SDRausty** [comment]
> run some x86 apps while working with aarch64 CPU?

@JanuszChmiel the mirrorlist and specific instructions for installing x86 are at this [archlinux32](http://www.archlinux32.org/download/) link.  These are the available Arch Linux architectures on an aarch64 smartphone:

```
[12:00~]$ uname -m
aarch64
[12:00~]$ startarch+armeabi-v7a c uname -m
armv7l
[12:00~]$ startarch+x86_64 c uname -m
x86_64
[12:01~]$ startarch+x86 c uname -m
i686
[12:01~]$ startarch c uname -m
aarch64
```

**Comment by SDRausty** [comment]
@JanuszChmiel there are upstream difficulties with https://bbs.archlinux32.org/viewtopic.php?pid=7409 on smartphone:
> newer root file systems are unavailable for download

> newer isos available here: https://archive.archlinux32.org/iso/

Alas an iso is not a rootfs and cannot be used to install Arch Linux without a CD/DVD drive.

**Comment by SDRausty** [comment]
[>  Maybe someone with the bandwidth, expertise, hardware and time will step forward and resolve this matter of rootfs publication for Arch Linux 32.  One the questions that I have is:  Can the root file system be incorporated into Arch Linux 32 https://archive.archlinux32.org/iso/ like it was in 2017 for Arch Linux https://archive.archlinux.org/iso/2017.03.01?  If so how?](https://bbs.archlinux32.org/viewtopic.php?pid=7447)

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/eeada6bbbdf1827d5940e7c39980f0e295ee0695 updates the status of Arch Linux 32 in arm architecture.

**Comment by SDRausty** [comment]
> Where's the source code to Arch Linux 32 iso creation and publication? 

[abaumann](https://bbs.archlinux32.org/profile.php?id=196109)
replied https://bbs.archlinux32.org/viewtopic.php?pid=7448#p7448
> Last time I checked there where Vargrant scripts in https://git.archlinux32.org/releng/
and https://git.archlinux32.org/archiso32/.

**Comment by SDRausty** [comment]
> newer root file systems are unavailable for download

> newer isos available here: https://archive.archlinux32.org/iso/

[levi](https://bbs.archlinux32.org/profile.php?id=166853) replied https://bbs.archlinux32.org/viewtopic.php?pid=7439#p7439

> If you want to do the work to enable it then sure.  Otherwise we're really just a hobbyist project, and the filesystem is there, we leave it up to you to pack it up as you want to.

Does anyone have a dusty old computer box with peripherals stored away that can be revived to run Arch Linux 32 without emulation to create a publishable root file system?

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/03e5ed9d3b20c2adb9c50d47effcd8591ce5c4fc automated qemu refresh; `setupTermuxArch qemu refresh`.

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/0d5c115400eae1f26bf5c7877613687abd59c5e5 updates contact information for Arch Linux x86 and x86_64 distributions and also updates the Arch Linux x86 mirrorlist.

**Comment by SDRausty** [comment]
Reprint from [bbs.archlinux32.org](https://bbs.archlinux32.org/viewtopic.php?pid=7459#p7459):
> I have updated the automation of the Arch Linux 32 qemu installation for Android today;  The mirror list and resolve config improvements install the system in two taps on modern smartphones. It appears that the root file system published back in 2017 is updatable:
`Total Download Size:   116.71 MiB
Total Installed Size:  455.75 MiB
Net Upgrade Size:      124.48 MiB`

>The errors mentioned at the beginning of this issue still linger and prevent the Arch Linux 32 system from updating properly.  Output when trying to install the sudo package:
`error: sudo: signature from "Erich Eckner (just to sign arch packages) <arch-packages@eckner.net>" is unknown trust
:: File /var/cache/pacman/pkg/sudo-1.9.3.p1-1.0-i686.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.`

>What is the simplest way to resolve this error without creating and publishing an updated root file system?

**Comment by SDRausty** [comment]
It appears that installing the key, and then this [http://archive.archlinux32.org/packages/p/pacman/pacman-5.2.1-1.4-i686.pkg.tar.xz](https://bbs.archlinux32.org/viewtopic.php?pid=7460#p7460) package can move this issue forward without an updated published root file system.

**Comment by SDRausty** [comment]
A solution is found! @WMCB-Tech confirmed and wrote:
> @SDRausty this is the setup process that i gone through and works fine as intended:
![IMG_20201022_141528.jpg](https://user-images.githubusercontent.com/65075766/96832552-86c74b80-1471-11eb-81bd-3f97db7ffb65.jpg)

There are more details [here](https://github.com/SDRausty/TermuxArch/issues/259?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEyNTc2MTU0Njg6Mjc3NDI0NTc%3D#issuecomment-714560072) and [here](https://bbs.archlinux32.org/viewtopic.php?pid=7460#p7460).

**Comment by SDRausty** [comment]
One of the testharnesses used in attempting to resolve this issue for emulated x86 computer architecture in Android:

```
setupTermuxArch p
mkdir ~/arch ; cp ~/archlinux-bootstrap-2017.03.01-i686.tar.gz ~/arch/
setupTermuxArch q
```

File [`knownconfigurations.bash`](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L14) has information about testing this configuration and installation script:

`KEEP=1			##  change to 0 to keep downloaded image;  Testing the installation process repeatedly can be made easier and lighter on your Internet bandwith and SAR with 'KEEP=0' and this fragment of code  'mkdir ~/arch; cp ~/ArchLinux*.tar.gz* ~/arch/' and similar.  The variable KEEP when changed to 0 (true) will keep the downloaded image and md5 files instead of deleting them for later reuse if desired.  The root file system image and md5 files can be saved and used again on subsequent installs when testing the install feature with this and similar fragments of code.`

**Comment by SDRausty** [comment]
[Levi wrote](https://bbs.archlinux32.org/viewtopic.php?pid=7468#p7468):
> will finally become the only real use for this old project [Arch Linux 32]

Minimum space required to install the installation on device (Android smartphone) can also be a strong motivator here:
1. aarch64 1500MB
2. arm7 1250MB
3. x86_64 800MB

The minimum install size for Arch Linux 32 appears to be around 400 megabytes.

**Comment by SDRausty** [comment]
This commit  https://github.com/TermuxArch/TermuxArch/commit/892c432363df7070f88f4368001e41b0f6f776d5 currently customizes for Arch Linux 32 with this code:
[`X86INT="whoami ; curl -OL http://archive.archlinux32.org/packages/p/pacman/pacman-5.2.1-1.4-i686.pkg.tar.xz ; pacman -U pacman-5.2.1-1.4-i686.pkg.tar.xz ; rm -f pacman-5.2.1-1.4-i686.pkg.tar.xz ; gpg --keyserver keyserver.ubuntu.com --recv-keys 0x194e37a47a4c671807bacb37b1117bc1094ea6e9 ; whoami"`](ttps://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L535)

**Comment by SDRausty** [comment]
The Arch Linux 32 system now installs and configures as expected with [this commit](https://github.com/TermuxArch/TermuxArch/commit/3f85f5bc8f89a8f5b5a20b9fb40914645b6d1422).   This issue is now fully resolved as all five architectures of Arch Linux install and configure as expected in Android.

Note: The TermuxArch command 'orcaconf'  designed to assist visually impaired users of Arch Linux also appears to work correctly in Arch Linux 32.

**Comment by SDRausty** [comment]
> it would be very interesting experiment.

The very interesting experiment is now active as this issue is closed.  Please participate and share your thoughts.  At present these emulation options are present; `setupTermuxArch qemu` and `setupTermuxArch unicorn`:
`./setupTermuxArch h|f emulation`

`[q[emu] [refresh] [customdir]]  Install alternate architecture on smartphone with https://github.com/qemu/QEMU emulation. Issue [Implementing QEMU #25](https://github.com/TermuxArch/TermuxArch/issues/25) has more information.`

`[u[nicorn] [refresh] [customdir]]  Partial Implementation:  Install alternate architecture on smartphone with https://github.com/unicorn-engine/Unicorn emulation.  This option currently defaults to option qemu as it is a partial implementation. Issue [Implementing QEMU #25](https://github.com/TermuxArch/TermuxArch/issues/25) has more information.`

**Comment by SDRausty** [comment]
What is your impression of QEMU emulation in Android?

I would like to add one more emulator; It is called [`Unicon`](https://github.com/unicorn-engine/Unicorn).  Have you tried [`Unicon`](https://github.com/unicorn-engine/Unicorn) emulation in your smartphone?

_Originally posted by @SDRausty in https://github.com/TermuxArch/TermuxArch/issues/34#issuecomment-721443756_

**Comment by JanuszChmiel** [comment]
I have never tried Unicon before.
I have tried Alpine term which contain preconfigured Qemu. Alpine term have
ooted whole Linux kernel and other sub systems.
 
Speed is very slow. But if somebody would use expensive very fast mobile
phones, it would not be so bad.
 
I have also tried bochs or similar Android apps based on Qemu.
The positive aspect of emulated environment based on The Termux and
Alpineterm package is The 100% accessible environment so visually impaired
user can monitor even kernel messages while system is being booted. Bash
shell and other text based apps are also producing accessible text output.
So Android screen readers can work with this operating system. 
If you will try to use Unicon please try to add some script which will
download .iso automatically and user will have The chance to try it and test
more effectively.
Since copying data from one folder to other and manually making some changes
to only try some bootable iso is limiting factor for testers.
I also know, that it is not correct to compare emulator with Proot.
Proot is being working at other principles than Qemu or other modules based
on it.
Qemu emulate CPU hardware, Proot uses special routines to monitor system
calls and those routines are reacting on many situations. But C code uses
CPu and RAM and Proot do not emulate CPU like Qemu.
Proot also contain some special source code file which monitor CPu
registers. It si complex C app. But I must confirm, that its speed will be
always The fastest possible.
Since not rooted devices can not use Kqemu Qemu accelaration Qemu kernel
module.
The advantage of Qemu booted distros is, that it is regular Linux, all Linux
possible wotking kernel modules will work.
This is not possible when using Proot. Since Proot do not emulate CPU it do
not emulate computer PCI and other hardware system resources.

**Comment by SDRausty** [comment]
> I have never tried Unicon before.

Neither have I managed to get Unicon working like QEMU.  When this issue was opened I knew QEMU should work as expected.

Then I had read about Unicorn.  Currently, I would like to know how to use  [`Unicon`](https://github.com/unicorn-engine/Unicorn) emulation.  Then it would be easier to implement  [`Unicon`](https://github.com/unicorn-engine/Unicorn) emulation into TermuxArch.

**Comment by SDRausty** [comment]
As option `setupTermuxArch qemu` option 4) x86 appears to have difficulty functioning as expected, this issue is reopened.

**Comment by SDRausty** [comment]
Quote from [bbs.archlinux32.org](https://bbs.archlinux32.org/viewtopic.php?pid=7522#p7522):

> Even if stability with the approach that [we have taken now](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L585) is reachieved ([updating the ancient 2017 root file system](https://archive.archlinux.org/iso/2017.03.01/), as opposed to publishing a current rootfs along with the published Arch Linux 32 isos the Arch Linux 32 project graces us with), I believe publishing an updated rootfs is the most stable approach to resolving this topic.

**Comment by JanuszChmiel** [comment]
I have typed
./setupTermuxArch.2 qemu
Installer have downloaded very probably normal file system with Archlinux
which is being directly executed by Proot.
How can I try real Qemu emulation?
Or my impressio is wrong and if I will use qemu option and option 4 in The
prompt screen, system will really download file system which will be
executed by Qemu? Not only by using Proot without qemu?

**Comment by SDRausty** [comment]
> How can I try real Qemu emulation?

You **are using** real QEMU emulation @JanuszChmiel; You can check with the `pkg list-installed | grep qemu` command in vannila Termux.

**Comment by JanuszChmiel** [comment]
Because setupTermuxarch.bash
 q
Allow Me only to choose The architecture so I choose 4 number.
But I Am see error that au or similar command not found.
So is it really possible to try I386 ArchLLinux with qemu?
Or I must be patient since it is not possible for now and everything must e
patiently developed to achieve this goal?

**Comment by SDRausty** [comment]
It appears that all of the Arch Linux versions once more install and configure with this https://github.com/TermuxArch/TermuxArch/commit/a5672d48f7af7ae130eb5269905681958b4d10d4 commit, including Arch Linux 32.  After running `setupTermuxarch qemu` you can choose option 4) x86 to access thr Arch Linux 32 distribution. 

Please share how the update went @JanuszChmiel.  It appears that the TermuxArch command `orcaconf` works Arch Linux 32 too.

**Comment by SDRausty** [comment]
> Arch Linux 32

Work notes about updating the Arch Linux 32 configuration in TermuxArch are at [docsTermuxArch](https://github.com/TermuxArch/docsTermuxArch/tree/master/issues/TermuxArch/25).  The update sequence was initially expanded.  Then it was reduced to the seven steps currently used.  This got the Arch Linux 32 update to run successfully once more in TermuxArch.

**Comment by SDRausty** [comment]
>  Unicon working like QEMU

Active 20201112 discussion thread at https://www.reddit.com/r/termux/comments/jsa4b6/ive_successfully_installed_unicorn/ and addition is debated:

> QEMU is a complete emulator ready for use.

> Unicorn is a CPU emulator engine, a library providing a APIs for running binary code on emulated CPUs. Start with https://www.unicorn-engine.org/docs/tutorial.html if you are interested in this.

**Comment by SDRausty** [comment]
Please see [`proot info: vpid 1: terminated with signal 11 #141`](https://github.com/termux/proot/issues/141) regarding why this issue is reopened.

**Comment by SDRausty** [comment]
Please see [`proot info: vpid 1: terminated with signal 11 #141`](https://github.com/termux/proot/issues/141) regarding why this issue is reopened.

> This error continues only to occur on armv7l architecture; aarch64 `qemu-user-i386` and `qemu-user-x86_64` architecture packages work as expected.

**Comment by SDRausty** [comment]
> run my favourite audio games for visually impaired

I would like to share the latest 'audio games' milestone with you here in this issue @JanuszChmiel:

```
user05:20~$ yay ghcup-hs
1 aur/ghcup-hs-bin 0.1.17.4-3 (+10 0.04)
an installer for the general purpose language Haskell
```
<hr>

GHCup-hs works flawlessly in [TermuxArch](https://github.com/TermuxArch/TermuxArch);  THANK YOU!  Did you know that Haskell can play music from code? [Tap here to see video search results.](https://www.ecosia.org/videos?q=haskell%20language%20%22making%20music%22%20%22source%20code%22)

[Sample haskell music output.mp4](https://user-images.githubusercontent.com/27742457/151226841-d11e98af-75a8-41c4-8862-fb2fa219e034.mp4) 

[Link to this sample of Haskell music source code.](https://github.com/tsoding/haskell-music/blob/master/Main.hs)

Can anybody else who uses Termux please try it?  I would like to hear your opinion about the way Haskell makes music from code in Termux please.

_Originally posted by @SDRausty in https://github.com/termux/termux-packages/issues/8758#issuecomment-1021855415_

**Comment by JanuszChmiel** [comment]
I have spent some time to found AN reliable and possible way to run X86 Windows apps.
It is possible thanks to 

https://github.com/ptitSeb/box86
But project must be run under Linux distribution which is ARM32 Bit, not AArch64 Bit one. And unfortunately, Termux do not allow users to choose which architecture user would want to use. It simply automatically download bootstrap files according To the automatically detected CPU architecture.

It is not A problem if user do not want to run box86.

Next problém is, that it is necessary to obtain X86 Windows prefix, Wine Windows files which mmust be X86.

So my dream would be too complex to reach for now.

**Comment by SDRausty** [comment]
>  I would like to hear your opinion about the way Haskell makes music from code in Termux please.

**Comment by SDRausty** [comment]
> under Linux distribution which is ARM32 Bit, not AArch64

I am checking the availability of box86 in Arch Linux 32;  Have you tried box86 in Arch Linux32?

**Comment by SDRausty** [comment]
> too complex to reach for now

> availability of box86 in Arch Linux

Arch Linux aarch64 `yay box86` result:
```
user08:08~$ yay box86
2 aur/box86 0.2.4-2 (+2 0.01)
    Linux Userspace x86 Emulator with a twist
1 aur/box86-git v0.2.4.r22.g4813a35e-1 (+3 0.01)
    Linux Userspace x86 Emulator with a twist
```

QEMU Arch Linux system emulation might not be neccessary to run box86 on our Android smartphones.

**Comment by JanuszChmiel** [comment]
Yes I will try it but I must remove older Termux and I must upgrade to 118 version. I had issues with makeyay script and I did not set user password for janusz so I could not use Sudo which makeyay script call. So I must reinstall Whole Termux and ArchLinux but I will 100 % try yay ghcup-hs command and I will try Haskel and its play sound feature. I believe, that it will support Pulseaudio for Termux.

**Comment by SDRausty** [comment]
> did not set user password

Since Termux is a one app and one user environment with the same permission scheme, does it make any sense to use passwords once a Termux session is opened?

**Comment by SDRausty** [comment]
> Can anybody else who uses Termux please try it?

> Yes I will try it

I have made an new issue [Run my favourite audio games for visually impaired #68](#68) for in depth discussion regarding creating music with Haskell in TermuxArch.

If you have difficulty installing `box86` in TermuxArch, please open a new issue or comment in #68 as this one is already very long.

**Comment by SDRausty** [comment]
[# two AUR ghcup packages](https://github.com/TermuxArch/TermuxArch/commit/35fc5b11b16b49a7f5c1f5f41a4c845495c8169c)

**Comment by ShapeShifter499** [comment]
Does this still work? it's hanging at ```Downloading from http://mirror.rackspace.com... This may take a long time pending connection```

trying to ```bash setupTermuxArch.sh qemu``` and selecting option 5 for ```x86_64```

EDIT: Also seeing this, might want to update the script. 
```
Package qemu-user-x86_64 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  qemu-user-x86-64
```
