### ISSUE TITLE
How to build Gradio without yay by using existing preconfigured aarch64 repositories

### ISSUE THREAD

**Issue by JanuszChmiel** [TermuxArch/TermuxArch#26]
Even though Gradio search station engine do not work, because radio-browser.info WEB portal have been changed, so Vala code is helpless to work with changed WEB site to provide search results, Gradio would be perfect and fully accessible solution for visually impaired user and if somebody advanced Vala expert could take some time and if this expert could adapt Gradio source to reflect todays and also future radio-browser.info WEB domain updates,, this radio player could be interesting alternative. to other players available.
Vala knowledge even would allow somebody to implement recording capabilities. It is possible to legally clone original Gradio repo to someones Github account and Gradio development can continue, MR Haecker will very probably not be engry because of it, because we are living in The world of full opensource freedom.

So how to install and build Gradio?
First of all
pacman -S  desktop-file-utils gobject-introspection gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gstreamer json-glib libgee libsoup sqlite3 appstream-glib gettext yelp-tools gst-libav vala
Then install git and clone The repo by using The following command.

git clone https://github.com/haecker-felix/Gradio.git
meson --prefix=/usr build

ninja -C build

ninja -C build install
Gradio could be normally executable and usable.
Try to search for AN station. YOu will very probably not get any results. If you will use mate-terminal gnome-terminal or if you will simply watch output generated by Vala by using normal Termux window, you will see The error. The .vala file source name and The line number. So Vala expert could even try to recode The corresponding source file to reflect latest
radio-browser.info
WEB page changes so build in search engine could work.
It is not dangerous system driver or kernel module modiffication so there are safe ways to debug and experiment. It is normal user app and Vala has reach run-time error engine and including C libraryes too.
I will inform you about my fight with Shortwave. Thanks to Rust community, which are very kind and helpfull, I had A chance to build and compile to binary form. But it was not been enough. I had experienced issues with Libhandy library.

**Comment by JanuszChmiel** [comment]
Sure, it is also necessary to install meson
pacman -S meson
Gradio have been my most favourite radio player for Linux. Fully accessible,
fast and memory friendly. Sure. Rust language programmers have made better
memory management than Vala experts, but this could be rather programmers
debate between Vala and Rust developers.
BUt app have normally worked.

**Comment by SDRausty** [comment]
> So how to install and build Gradio?

Please type the following at the command prompt to build `gradio`. It might take a little while for these commands to complete. If everything goes well you will have built and installed `gradio` in your smartphone:
1. `[14:05~]$ startarch l user`,
1. `[user14:05~]$ makeyay`,
1. `[user14:14~]$ yay gradio` # will generate errors.  These next couple of steps should lead to a successful build and install,
1. `[14:25~]$ startarch el user` **# please note this brand new option** is not the same as `startarch l user` and cannot install all the packages like the `l` login can due to hard link to soft link proot translation.  Delete the build directory in `~/.cache/yay/` if there are build errors to rebuild.  Initially rebuild with command `yay gradio`  Adjust file PKGBUILD accordingly:
   1. Change architecture to any in file PKGBUILD,
   1. Add `sudo` before the offending command in the function that generates an error in file PKGBUILD,
   1. Use command `makepkg -irs --noconfirm` to build and install `gradio`,
1. Enjoy:

```
[user14:36dbus-x11]$ yay gradio
2 aur/gradio-git 7.1-1 (+8 0.00) (Out-of-date: 2018-11-28)
    A GTK3 app for finding and listening to internet radio stations
1 aur/gradio 7.3-1 (+55 0.03) (Installed)
    A GTK3 app for finding and listening to internet radio stations
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 
```

**Comment by SDRausty** [comment]
> 2 aur/gradio-git 7.1-1 (+8 0.00) (Out-of-date: 2018-11-28)

> https://github.com/haecker-felix/Gradio.git

> This repository has been archived by the owner. It is now read-only.

**Comment by JanuszChmiel** [comment]
Ys. Unfortunately, Gradio is outdated. It have worked several month ago
before radio-browser.info WEB page have been redesigned, so
radiostationsprovider.vala source can not work with search WEB page.
It is sad, that it will not be easy to recode .vala source to support new
web page.
Shortwave is good for sighted majority. But its GUI is not very accessible
for visually impaired users.
To stop to be sad, I will rather try seamonkey with
radio-browser.info
WEB page if its build in player inside this WEB site will work with Termux.
Since my programmers skills are not so good to recode Gradio vala sources to
support new radio-browser.info WEB site.
Gradio uses this site to search for stations.

**Comment by JanuszChmiel** [comment]
I have A good notice for you. ArchLinux AArch64 packagers and other packager
developers have not done something wrong to prevent Orca from functioning by
using Termux. So I can perfectly use Orca. I Am now configuring Mate-control
center to support Bluetooth external keyboard hot keys. As A result, I can
perfectly still use many apps. I will only remove mate-power-manager since
it cause C language realted creash, since we are not using standard Linux
system with UDEV enabled, ETC. FOrtunately, It is possible to remove this
without affecting Mate.

**Comment by SDRausty** [comment]
```
[14:54~]$ startarch el user
[user14:54~]$ yay meson
```
Please keep in mind that if you want to install packages with symlinks to use the option `startarch el user` first.
```
3 aur/meson-git 0.55.0.r73.6006987ce-1 (+6 0.56)
    SCons-like build system that use python as a front-end language and Ninja as a building backend
2 aur/mingw-w64-meson 1-19 (+6 0.23)
    Meson wrapper for MinGW (mingw-w64)
1 extra/meson 0.55.1-1 (1006.9 KiB 6.1 MiB) (Installed)
    High productivity build system
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 3
```
```
writing manifest file 'meson.egg-info/SOURCES.txt'
Copying meson.egg-info to /home/user/.cache/yay/meson-git/pkg/meson-git/usr/lib/python3.8/site-packages/meson-0.55.999-py3.8.egg-info
error: [Errno 13] Permission denied: '/home/user/.cache/yay/meson-git/pkg/meson-git/usr/lib/python3.8/site-packages/meson-0.55.999-py3.8.egg-info/PKG-INFO'
==> ERROR: A failure occurred in package().
    Aborting...
error making: meson-git
[user14:57~]$ cd .cache/yay/meson-git/
```
Add sudo before `python setup.py install --root="$pkgdir" --optimize=1` to function package() in file PKGBUILD.  These are the results:
`3 aur/meson-git 0.55.0.r73.6006987ce-1 (+6 0.56) (Installed: 0.55.0.r217.4c2d0eb9b-1)`

How are your results?

**Comment by JanuszChmiel** [comment]
Radio-browser.info WEB radio player is fully compatible with Seamonkey and I
can play all streams with no issue.
My loving Seamonkey. Fortunately, some packager expert is doing his best to
prepare up to date AArch64 version. It is complex to build this program.
FOrtunately, ArchLinux community contain many clever people.

**Comment by SDRausty** [comment]
> Vala code is helpless to work

```
[15:31~]$ startarch el user
[user15:31~]$ yay mate-git
.
.
.
1 aur/vala-panel-appmenu-mate-git 0.7.4-1 (+34 0.03)
    AppMenu (Global Menu) plugin for mate-panel
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
.
.
.
==> Entering fakeroot environment...
==> Starting package()...                                              
ninja: Entering directory `build'                                      
[1/21] Generating version.h with a custom command
Installing data/org.valapanel.application.desktop to /home/user/.cache/yay/vala-panel-git/pkg/vala-panel-git/usr/share/applications           
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...                
Error getting authority: Error initializing authority: Could not connect: No such file or directory
==> ERROR: A failure occurred in package().                                Aborting...                                                        
error making: vala-panel-git
[user15:41~]$ e                                                        
logout
[15:41~]$ startarch el user
[user15:41~]$ yay mate-git
.
.
.
==> Entering fakeroot environment...
==> Starting package()...
ninja: Entering directory `build'
[1/21] Generating version.h with a custom command
Installing data/org.valapanel.application.desktop to /home/user/.cache/yay/vala-panel-git/pkg/vala-panel-git/usr/share/applications
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Error getting authority: Error initializing authority: Could not connect: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: vala-panel-git
[user15:42~]$ cd ~/.cache/yay/vala-panel-appmenu-xfce-git/
[user16:03vala-panel-appmenu-xfce-git]$ sed -i 's/meson install/sudo meson install/g' PKGBUILD`
[user16:06vala-panel-appmenu-xfce-git]$ sed -i "s/i686\' \'x86_64/any/g" PKGBUILD
[user16:06vala-panel-appmenu-xfce-git]$ f any PKGBUILD                 
142:  arch=('any')  # there is one more at it before success
.
.
.
# this command built it
[user16:07vala-panel-appmenu-xfce-git]$ makepkg -irs --noconfirm
```
@JanuszChmiel you have made three references to vala. 
I am not sure if I am following you correctly and if this is the package mentioned?

**Comment by SDRausty** [comment]
> Vala code is helpless to work

Please note the first attempt to build the Arch Linux vala-panel-git package on smartphone is with login `startarch l user`, the second try which is successful is with login `startarch l user`:
```
[15:31~]$ startarch l user
[user15:31~]$ yay mate-git
.
.
.
1 aur/vala-panel-appmenu-mate-git 0.7.4-1 (+34 0.03)
    AppMenu (Global Menu) plugin for mate-panel
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
.
.
.
==> Entering fakeroot environment...
==> Starting package()...                                              
ninja: Entering directory `build'                                      
[1/21] Generating version.h with a custom command
Installing data/org.valapanel.application.desktop to /home/user/.cache/yay/vala-panel-git/pkg/vala-panel-git/usr/share/applications           
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...                
Error getting authority: Error initializing authority: Could not connect: No such file or directory
==> ERROR: A failure occurred in package().                                Aborting...                                                        
error making: vala-panel-git
[user15:41~]$ e                                                        
logout
[15:41~]$ startarch el user
[user15:41~]$ yay mate-git
.
.
.
==> Entering fakeroot environment...
==> Starting package()...
ninja: Entering directory `build'
[1/21] Generating version.h with a custom command
Installing data/org.valapanel.application.desktop to /home/user/.cache/yay/vala-panel-git/pkg/vala-panel-git/usr/share/applications
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Error getting authority: Error initializing authority: Could not connect: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: vala-panel-git
[user15:42~]$ cd ~/.cache/yay/vala-panel-appmenu-xfce-git/
[user16:03vala-panel-appmenu-xfce-git]$ sed -i 's/meson install/sudo meson install/g' PKGBUILD`
[user16:06vala-panel-appmenu-xfce-git]$ sed -i "s/i686\' \'x86_64/any/g" PKGBUILD
[user16:06vala-panel-appmenu-xfce-git]$ f any PKGBUILD                 
142:  arch=('any')  # there is one more similar change to be done in this file before success, and this is done by changing the architecture to any in another line in a similar way again in this file.
.
.
.
# the `makepkg -irs --noconfirm` command built it
[user16:07vala-panel-appmenu-xfce-git]$ makepkg -irs --noconfirm
```
@JanuszChmiel you have made references to vala in your comments about building packages. I am not sure if I am following you correctly, and if this is the package that you mentioned?

**Comment by SDRausty** [comment]
> Vala code is helpless to work

Please note the first attempt to build the Arch Linux vala-panel-git package in Termux PRoot on smartphone is with login `startarch l user` and uses command `yay mate-git`.  The second try which is successful is with login `startarch el user` and command `makepkg -irs --noconfirm`.  Please note the difference between the two types of logins:
```
[15:31~]$ startarch l user
[user15:31~]$ yay mate-git
.
.
.
1 aur/vala-panel-appmenu-mate-git 0.7.4-1 (+34 0.03)
    AppMenu (Global Menu) plugin for mate-panel
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
.
.
.
==> Entering fakeroot environment...
==> Starting package()...                                              
ninja: Entering directory `build'                                      
[1/21] Generating version.h with a custom command
Installing data/org.valapanel.application.desktop to /home/user/.cache/yay/vala-panel-git/pkg/vala-panel-git/usr/share/applications           
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...                
Error getting authority: Error initializing authority: Could not connect: No such file or directory
==> ERROR: A failure occurred in package().                                Aborting...                                                        
error making: vala-panel-git
[user15:41~]$ e                                                        
logout
[15:41~]$ startarch el user
[user15:41~]$ yay mate-git
.
.
.
==> Entering fakeroot environment...
==> Starting package()...
ninja: Entering directory `build'
[1/21] Generating version.h with a custom command
Installing data/org.valapanel.application.desktop to /home/user/.cache/yay/vala-panel-git/pkg/vala-panel-git/usr/share/applications
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Error getting authority: Error initializing authority: Could not connect: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: vala-panel-git
[user15:42~]$ cd ~/.cache/yay/vala-panel-appmenu-xfce-git/
[user16:03vala-panel-appmenu-xfce-git]$ sed -i 's/meson install/sudo meson install/g' PKGBUILD`
[user16:06vala-panel-appmenu-xfce-git]$ sed -i "s/i686\' \'x86_64/any/g" PKGBUILD
[user16:06vala-panel-appmenu-xfce-git]$ f any PKGBUILD                 
142:  arch=('any')  # there is one more similar change to be done in this file before success, and this is done by changing the architecture to any in another line in a similar way again in this file.
.
.
.
# the `makepkg -irs --noconfirm` command built it
[user16:07vala-panel-appmenu-xfce-git]$ makepkg -irs --noconfirm
```

The difference between the two login types is that the first can translate symlinks.  The second  login type cannot translate symlinks.  This means that if you are installing packages the first login type is preferred.  

However, if you are building packages the second type is wanted because the builds seem to go smoother.  One way of testing this difference is using install `git` and the `git` commands with both types of logins.  Removing the cloned directory is part of this test too.

@JanuszChmiel you have made references to vala in your comments about building packages. Is the `vala-panel-appmenu-xfce-git` one of packages that you have mentioned?

**Comment by JanuszChmiel** [comment]
Oh I understand you. You want to use yours build approach. No problem. But
believe Me. Gradio do not work not because of build problems. It is really
because radio-browser.info uses different page format.
So searchstations provider.vala or similar name can not search for stations.
So problem is that somebody would had to try to reprogramm this .vala source
module so it will reflect new radio-browser.info WEB page for searching
stations.

**Comment by JanuszChmiel** [comment]
Dear kind MR Rausty,
I have mean Vala programming language. Vala is perfectly precompiled on
available ArchLinux repos. The problem is not with Vla itself. The problem
is caused by The fact, That Gradio developer have coded his app in The
times, when 
radio-browser.info
domain The WEB site for searching radio stations have been made by other way
than today. As A result, Gradio source code contain algorithm to communicate
with this WEB site, which is not supported now, because radio-browser.info
WEBpage code have been changed by their authors.
I will look inside The source code to find out, how to repair ito allow
search for stations.
Gradio have used radio-browser.info WEB site to search and open radio
streams.
The routine which have been invented by MR Haecker is fast and reliable. But
it do not work thanks to changes of
radio-browser.info

**Comment by SDRausty** [comment]
> to reflect new radio-browser.info WEB page for searching stations.

From what you say this appears to be **a very small change that is desired** in the source code.  Can you point us to the source page please?

**Comment by SDRausty** [comment]
> want to use your build approach. No problem.

The build approach is Arch Linux's build system.  One of the reasons it did not work until last month is hard link to soft linked translations and the way logins handle this task.

**Comment by SDRausty** [comment]
> want to use your build approach. No problem.

The build approach is Arch Linux's build system.  One of the reasons it did not work until last month is hard link to soft linked translations and the way logins handle this task.  

This is why the new login option `elogin` has been developed.  I really would like to hear user opinions as to which option they prefer with specific tasks.

As I mentioned this is a **brand new option**.  It is **not an experimental option** because this option had also been configured as a standard login for years.  

As it turns out both login configurations are now highly desired with the recent improvements to TermuxArch in August 2020.  This is why the `elogin` option was added.

**Comment by SDRausty** [comment]
> want to use your build approach. No problem.

The build approach is Arch Linux's build system.  One of the reasons it did not work until last month is hard link to soft linked translations and the way logins handle this task.  

This is why the new login option `elogin` has been developed.  I really would like to hear user opinions as to which option they prefer with specific tasks now that it is implemented.  As I mentioned this is a **brand new option**.  It is **not an experimental option** because this option had also been configured as a standard login for years.  

As it turns out both login configurations are now highly desired with the recent improvements to TermuxArch in August 2020.  This is why the `elogin` option was added, and   I really would like to hear user opinions as to which option they prefer with specific tasks now that it is implemented.

**Comment by JanuszChmiel** [comment]
The soure page is really
www.radio-browser.info
Here are error messages which appear when You will click on The radio button
to search for AN station.
(gradio:25597): CRITICAL **: 20:23:54.271: gradio-category-items.vala:99:
Cou
 ld not load category items: <data>:1:1: Chyba zpracování: unexpected
character `
 <', expected value

 

 ** (gradio:25597): WARNING **: 20:23:54.277:
gradio-station-provider.vala:73: Ab
 orted parsing search results! <data>:1:1: Chyba zpracování: unexpected
character
  `<', expected value

 

 ** (gradio:25597): WARNING **: 20:23:54.278:
gradio-station-provider.vala:73: Ab
 orted parsing search results! <data>:1:1: Chyba zpracování: unexpected
character
  `<', expected value

 

 ** (gradio:25597): WARNING **: 20:23:54.353:
gradio-station-provider.vala:73: Ab
 orted parsing search results! <data>:1:1: Chyba zpracování: unexpected
character
  `<', expected value

 ** Message: 20:23:55.242: gradio-searchbar.vala:213: Sending new search
request 
 to server

 

 ** (gradio:25597): WARNING **: 20:23:55.536:
gradio-station-provider.vala:73: Ab
 orted parsing search results! <data>:1:1: Chyba zpracování: unexpected
character
  `<', expected value

 
So it is necessary to deeply analyse The name of .vala source files which
are The part of error messages and recode those files if it will be possible
so radio stations search function will work.

**Comment by SDRausty** [comment]
After using `yay gradio` and editing file `PKGBUILD` like so:
```
arch=('any')
sudo meson builddir --prefix=/usr
DESTDIR="${pkgdir}" sudo ninja -C builddir install
```
The entry arch is changed to **any** and meson and ninja are prefixed with **sudo**.  The command `makepkg -irs --noconfirm` builds and installs `gradio`:
```
[user19:57gradio]$ yay gradio
2 aur/gradio-git 7.1-1 (+8 0.00) (Out-of-date: 2018-11-28)
    A GTK3 app for finding and listening to internet radio stations
1 aur/gradio 7.3-1 (+55 0.02) (Installed)                                                                     A GTK3 app for finding and listening to internet radio stations
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
```
> recode those files if it will be possible
```
[user19:59gradio]$ find -iname "*vala*"
./src/Gradio-7.3/src/gradio-app.vala
./src/Gradio-7.3/src/gradio-audio-player.vala
./src/Gradio-7.3/src/gradio-category-items.vala
./src/Gradio-7.3/src/gradio-codec-installer.vala                                                          
./src/Gradio-7.3/src/gradio-collection.vala                                                               
./src/Gradio-7.3/src/gradio-details-box.vala                                                              
./src/Gradio-7.3/src/gradio-headerbar.vala                                                                
./src/Gradio-7.3/src/gradio-image-cache.vala                                                              
./src/Gradio-7.3/src/gradio-library.vala
./src/Gradio-7.3/src/gradio-main-window.vala
./src/Gradio-7.3/src/gradio-mainbox.vala                                                                  
./src/Gradio-7.3/src/gradio-menubutton.vala
./src/Gradio-7.3/src/gradio-mpris.vala
./src/Gradio-7.3/src/gradio-organize-collection-popover.vala
./src/Gradio-7.3/src/gradio-player-toolbar.vala
./src/Gradio-7.3/src/gradio-radio-browser.vala
./src/Gradio-7.3/src/gradio-radio-station.vala
./src/Gradio-7.3/src/gradio-search-provider.vala
./src/Gradio-7.3/src/gradio-searchbar.vala
./src/Gradio-7.3/src/gradio-selection-toolbar.vala
./src/Gradio-7.3/src/gradio-settings.vala
./src/Gradio-7.3/src/gradio-station-compare.vala
./src/Gradio-7.3/src/gradio-station-editor-dialog.vala                                                    
./src/Gradio-7.3/src/gradio-station-provider.vala
./src/Gradio-7.3/src/gradio-status-icon.vala
./src/Gradio-7.3/src/gradio-thumbnail.vala                                                                
./src/Gradio-7.3/src/gradio-utils.vala
./src/Gradio-7.3/src/groupbox/gradio-groupbox-button.vala
./src/Gradio-7.3/src/groupbox/gradio-groupbox-item.vala                                                   
./src/Gradio-7.3/src/groupbox/gradio-groupbox-switch-item.vala
./src/Gradio-7.3/src/groupbox/gradio-groupbox-widget-item.vala
./src/Gradio-7.3/src/groupbox/gradio-groupbox.vala
./src/Gradio-7.3/src/model/gradio-generic-model.vala
./src/Gradio-7.3/src/model/gradio-station-model.vala
./src/Gradio-7.3/src/page/gradio-collection-items-page.vala
./src/Gradio-7.3/src/page/gradio-library-page.vala
./src/Gradio-7.3/src/page/gradio-page.vala                                                                
./src/Gradio-7.3/src/page/gradio-search-page.vala
./src/Gradio-7.3/src/page/gradio-settings-page.vala
```
>  ** (gradio:25597): WARNING **: 20:23:55.536:
gradio-station-provider.vala:73: Ab
 orted parsing search results! <data>:1:1: Chyba zpracování: unexpected
character
  `<', expected value

It appears that this `./src/Gradio-7.3/src/gradio-station-provider.vala` file wants editing.  There might be other vala files that want recoding too.  Please share what changes you would make and their results.

Another way to try to find if gradio will work on your smartphone might be to build this package:
`2 aur/gradio-git 7.1-1 (+8 0.00) (Out-of-date: 2018-11-28)`

@JanuszChmiel please see if reaching out to gradio groupsin the Internet also helps in resolving making gradio work in your smartphone.
