### ISSUE TITLE
spacemacs with latest TermuxArch

### ISSUE THREAD

**Issue by lypanov** [TermuxArch/TermuxArch#27]
Unfortunately upgrading TermuxArch to get the termux-* scripts has left me with a broken primary use case, namely. I can no longer run emacs/spacemacs (Update: This is probably due to my transition from mixed Termux+TermuxArch to pure TermuxArch in fact).

The fix has already been discussed here:
  https://github.com/t184256/nix-on-droid/issues/12

But alas AFAICT this regression hasn't yet been fixed in proot.

**Comment by SDRausty** [comment]
> can no longer run emacs/spacemacs.
```
[user06:02~]$ pci spacemacs

==> Running TermuxArch pci spacemacs 2.0.542 ...

error: you cannot perform this operation unless you are root.
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
error: target not found: spacemacs
[user06:33~]$ yay spacemacs
no packages match search
[user06:36~]$ f emacs bin/pci
74:pacman --noconfirm --color=always -Syu base base-devel emacs "${@:2}" || sudo pacman --noconfirm --color=always -Syu base base-devel emacs "${@:2}"
77:pacman --noconfirm --color=always -Syu base base-devel emacs jdk8-openjdk "${@:2}" || sudo pacman --noconfirm --color=always -Syu base base-devel emacs jdk8-openjdk "${@:2}"
80:pacman --noconfirm --color=always -Syu base base-devel emacs jdk10-openjdk "${@:2}" || sudo pacman --noconfirm --color=always -Syu base base-devel emacs jdk10-openjdk "${@:2}"
[user06:36~]$ pacman -S emacs
error: you cannot perform this operation unless you are root.
[user06:36~]$ sudo pacman -S emacs
```
The command `sufo pacman -S emacs` works as expected, `emacs` as well.  @lypanov I do not understand what this issue has to do with TermuxArch?  Can you explain it in more detail to me please?

**Comment by SDRausty** [comment]
```
[user12:44.emacs.d]$ f clone README.md
35:    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
73:Just clone it, launch it, then press the space bar to explore the
152:`/Applications` directory. You still need to run the `git clone` mentioned at
```

I tried the method described in the README.md and yes, spacemacs does not work as you say @lypanov. I have read and studied the [scacemaxs' issues page](https://github.com/syl20bnr/spacemacs/issues) and it appears that spacemacs really does not work at all!  A total 699 [open issues](https://github.com/syl20bnr/spacemacs/issues) is a little bit too many in my opinion.  Do you agree?


> **Note:** Ubuntu LTS 12.04 and 14.04 repositories have only Emacs 24.3 available. You have to build from source Emacs 24.4 or greater, as Spacemacs won't work with 24.3. The same may be true for other distributions as well.

```
[user12:53.emacs.d]$ emacs --version
GNU Emacs 27.1
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
Have you tried rebuilding Emacs as suggested?
```
[user12:34.emacs.d]$ yay emacs
465 aur/emacs-neotree 0.5.2-1 (+0 0.00) (Orphaned)
    A emacs tree plugin like NerdTree for Vim.
```

There are almost 500 Emacs packages to choose from in Arch Linux in Termux PRoot in your smartphone.

> upgrading TermuxArch to get the termux-* scripts has left me with a broken primary use case

@lypanov how did you accomplish this?  The `termux-*` scripts are not implemented at present.

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/f96f2cce474385167539c8a217ae0d80b96e5d76 adds temporary developer support for these commands @lypanov: 
[`PRFXTOLS=(am dpkg getprop termux-change-repo termux-info termux-open termux-open-url termux-wake-lock termux-wake-unlock)`](https://github.com/TermuxArch/TermuxArch/commit/f96f2cce474385167539c8a217ae0d80b96e5d76#diff-96e6fc14454e2d4bf496fc2de0323d87R838) 

In order to access these commands, you can use the option `setupTermuxArch o`.  Diagnostic information will be helpful to improve this installation script.

**Comment by lypanov** [comment]
> ```
> [user12:44.emacs.d]$ f clone README.md
> 35:    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
> 73:Just clone it, launch it, then press the space bar to explore the
> 152:`/Applications` directory. You still need to run the `git clone` mentioned at
> ```
> 
> I tried the method described in the README.md and yes, spacemacs does not work as you say @lypanov. I have read and studied the [spacemaxs' issues page](https://github.com/syl20bnr/spacemacs/issues) and it appears that spacemacs really does not work at all! A total 699 [open issues](https://github.com/syl20bnr/spacemacs/issues) is a little bit too many in my opinion. Do you agree?

Still sad about this. Value this wonderful project and emacs not working really sucks 💔 . doom-emacs also doesn't work - it's not specific to spacemacs but an issue that packages in emacs seem to reproduce.

The underlying issue remains a bug in proot, but that seems to be pretty much unmaintained (based on the termux proot bug list... gosh!).

I'd really like to help, and hope you can aid me in it.

Nix-on-droid patched the proot used during the issue https://github.com/t184256/nix-on-droid/issues/12

Is there any way for me to workaround this and use a different proot binary? I've tried the migration to nix-on-droid but it's missing 99% of the work you've done to make TermuxArch so great! This remaining 1% is a massive pain point for me alas :(

It's my only remaining issue with working full time with TermuxArch since making the migration from a Surface Pro 3 to my Galaxy Tab S6.

**Comment by SDRausty** [comment]
> emacs not working

```
[user15:30~]$ emacs --version
GNU Emacs 27.1
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
> Nix-on-droid patched the proot used during the issue https://github.com/t184256/nix-on-droid/issues/12

Thank you for sharing about the patch;  I have found a Doom Emacs  https://github.com/termux/proot/issues/123 issue that was resolved; Can you share at https://github.com/termux/proot please?

**Comment by lypanov** [comment]
Ah brilliant find! I've been googling for months. Only today did I finally find the courage to give doom a try and noticed that it was also broken.

A termux pkg upgrade, restarted my sessions in TermuxArch and.... spacemacs now works flawlessly!

Thank you so much SDRausty! One of the biggest x-mas presents I'll get this year!! 🥳🥳🥳

**Comment by SDRausty** [comment]
You are welcome @lypanov; Thank you for sharing 🎵 🎶

**Comment by SDRausty** [comment]
The aliases and commands `ES` and `es` are added with commit https://github.com/TermuxArch/TermuxArch/commit/187fa1909c5ffec17d85ce415a2daa1182e459c8.
