### ISSUE TITLE
Todays up to date tigervnc can not be started on AARch64 architecture

### ISSUE THREAD

**Issue by JanuszChmiel** [TermuxArch/TermuxArch#28]
When I have performed ArchLinux upgrade by typing
pacman -Syu as root user
I have got tigervnc update.
Unfortunately, I can not run tigervnc at all.
Because I Am getting The following error.

vncserver: Couldn't find suitable Xsession

I do not know, if is it new revolutionar new approach from Tigervnc developers, which will allow only specific Xsessions? Or if there is An bug from developers or some hydden problem.
If is it new revolutionar version which will not allow us to run Tigervnc it will be necessary to downgrade to The previously functioning version. If yes, how to find it and I will have to build it.
I have even opened bug on Tigervnc Github page to get An assistance what has happened with Tigervnc when this new version have been released.

**Comment by SDRausty** [comment]
> Unfortunately, I can not run tigervnc at all.
```
[user16:43~]$ yay Tigervnc                                       
4 aur/qconnect 1.8.1-4 (+0 0.00)                                                  
Allows the running of reconnectable programs via torque with tmux, xpra, and tigervnc                                                                   
3 aur/tigervnc-viewer 1.7.0-1 (+7 0.00)                                           
TigerVNC (Viewer only), forked from the VNC 4 branch of TightVNC.         
2 aur/tigervnc-git r3764.3a37af3-1 (+13 0.00)                                     
Suite of VNC servers and clients. Based on the VNC 4 branch of TightVNC.  
1 community/tigervnc 1.11.0-2 (1.7 MiB 4.6 MiB)                                   
Suite of VNC servers and clients. Based on the VNC 4 branch of TightVNC.  ==> Packages to install (eg: 1 2 3, 1-3 or ^4)
```

Have you tried 2 aur/tigervnc-git?

**Comment by JanuszChmiel** [comment]
MR Rausty,
I have excellent news for you.
I have found my own way. I have simply stop to use vncserver ArchLinux script. And I have simply run my loving Tigervnc by using The following command.

Xvnc -localhost -geometry 1024x768 -depth 24 -SecurityTypes=None &
When I run Tigervnc by using this technique, everything work with no issues. Except one cosmetic think. When I run Tigervnc by using this approach, Tigervnc display its protocol directly to Terminal. Which is fortunately not big problem, because Tigervnc code do not write too much data on terminal.
I always do my best to find my own way to solve problems. I will be only hoping, that Tigervnc developers will not recode their app on future so it will really completely stop running on Android, Termux and Proot.
Thanks to Tigervnc, I can perfectly use all hotkeys with Orca including SHIFT+TAB. So I can remove X11vnc.
Very interesting fact.
Xvnc support shared memory which is currently implemented on Archsetup script. Very probably, because shmget and similar functions are not used.

**Comment by JanuszChmiel** [comment]
I have disabled mate screen saver and I will disable mate-power manager. I have done verybig on my life. That I have not studied informatic sciences. Because I could remove all routines from Mate desktop which intensively communicate with system bus. And as we know, Mate can be perfectly run even without system bus connection. Except one cosmetic problem. When using logout from Mate, not all processes are correctly terminated. So not all X11 session based processes are correctly terminated. Except Orca screen reader. Sure. I could start to experiment with Dbus special values which driver Dbus how many Milliseconds it should give processes to terminate, but it is not very soft work. And by using wrong values, I could simply en with very unstable system. I will try to debate with Dbus programmers about this problem related to logout problem from Mate. Because Mate C programmers can not make dual code for Termux and Proot situation and for standard Linux, since their work would become too complex and long term and mate-session and other similar compiled binaryes could get much more bigger syzes.

**Comment by SDRausty** [comment]
This https://www.reddit.com/r/archlinux/comments/iqjds6/tigervnc_11102_update_fix/ just came up yesterday.

> Starting a vnc session results in tigervnc: Could not start a suitable Xsession

**Comment by SDRausty** [comment]
@JanuszChmiel can you please share a PR regarding the workaround:

1. Fork git repository,
1. Make change,
1. Create a pull request.

This link has example PRs:
https://github.com/TermuxArch/TermuxArch/pulls?q=is%3Apr+is%3Aclosed

**Comment by SDRausty** [comment]
A PR is like a shortcut.  For example many words a couple lines of code

**Comment by SDRausty** [comment]
> A PR is like a shortcut, for example; many words = a couple lines of code and a function or two

a braille terminal might make the task of reading easier

**Comment by SDRausty** [comment]
You might not know which file to begin with regarding tigervnc should you choose to make a PR, and this seems quite understandable.  This file [`archlinuxconfig.bash`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash) has functions that make the TermuxArch commands and user configuration files that we use in Arch Linux in PRoot.  A reference to newly created functions should be added to function `_ADDADDS_` in file [`necessaryfunctions.bash`](https://github.com/TermuxArch/TermuxArch/blob/master/necessaryfunctions.bash).  Good luck 🧑‍🚒

**Comment by JanuszChmiel** [comment]
Dear Mr Rausty.
I will rather script manipulations on you and other who are sighteght. I
could corrupt The code. I will be very glad to find a work arounds, I will
test yay packages building, shared memory, but I will rather scripting on
others. Since I could make a chaos accidentally and I do not want to make
Yours scripts user sad thanks to my wrong operations. Since I do not want to
destroy yours positive project accidentally.
Reharding to shared memory. Shmget and similar functions do not work, but
thanks to .so library it is possible to even use shmget.
The programmers question is what is more smple. Extend Termux libraryes or
to extend .so android-shmem.so library.
The functioning tigerVNC command is
 
Xvnc -localhost -geometry 1024x768 -depth 24 -SecurityTypes=None &

**Comment by Yrosenz** [comment]
@JanuszChmiel I'm trying your method to start Xvnc but could not find where to define the session to be used.

**Comment by SDRausty** [comment]
@Yrosenz a note about exports related to 'start Xvnc':
It's just a simple command to setup the exports.  For it to work, it must be sourced.  That's why the dot `.` and space are important.   Otherwise, it won't work right:
```
[19:36 ~ ]$ . exd
[19:36 ~ ]$ export
declare -x DISPLAY=":0"
declare -x PULSE_SERVER="tcp:127.0.0.1:4712"
```

_Originally posted by @SDRausty in https://github.com/SDRausty/TermuxArch/issues/59#issuecomment-381285151_

The `exd` command can be expanded and similar commands can be made to assist with this issue;  Suggestions are welcome.

**Comment by SDRausty** [comment]
The recently undepreciated [`makeaurhelpers`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L664&&#L1054) command might also be helpfull in streamlining this issue;  Testing for `makeaurhelpers` is requested as this command was recently undepreciated and is significantly expanded.

**Comment by SDRausty** [comment]
https://github.com/SDRausty/termux-archlinux/issues/66
