### ISSUE TITLE
WARNING: Could not connect to systemd: Failed to connect to   socket /run/dbus/system_bus_socket: directory or file not exist

### ISSUE THREAD

**Issue by JanuszChmiel** [TermuxArch/TermuxArch#29]
Very probably, many of us ave seen this error when run some app by using Termux. To avoid those errors. I AM afraid, that complete Linux kernel would had to be used.
Next complex science fiction related possibility.
What if somebody would compile ArchLinux kernel which would only contain system Bus support module and code and nothing else. And what if so little kernel would be executed by using Qemu from running ArchLinux by using Proot? But there would be more complex technique. Recode Proot so every related system bus code would be directed to some communication pipe between Qemu and running little kernel with only system bus support and running app.
This spec ial technique if it could be implemented may be a big revolution on future.

**Comment by SDRausty** [comment]
@JanuszChmiel have you tried this command `csystemctl` which plugs a `systemctl` replacement into Arch Linux in PRoot.  This command was shared in the  summer of 2020 by @petkar with this commit  https://github.com/TermuxArch/TermuxArch/pull/10.

**Comment by JanuszChmiel** [comment]
I have not tried this command yet. BUt please, would you send Me exactly The
command which could solve this problem?
Which services should I execute by using csystemctl
Thank you. IT would be A miracle, if this new script could solve this
warning. Because mate-session intensively communicate with systemd.

**Comment by JanuszChmiel** [comment]
The question is if systemd can be activated by using this command. Because
mate-session need The connection to systemd and systemd want to connect to
system bus.
If I have understood it well.
Ssystemctl can start various services. Which services should I start?

**Comment by SDRausty** [comment]
> The question is if systemd can be activated by using this command.

This is a systemctl replacement:
https://github.com/TermuxArch/docker-systemctl-replacement

TermuxArch command `csystemctl` plugs the systemctl replacement into Arch Linux.

**Comment by JanuszChmiel** [comment]
Oh. And should I type this command
csystemctl 
as root or as a non root user such as janusz.
I have wrongly thought, that csystemctl  is only used to start services.

**Comment by SDRausty** [comment]
> as root or as a non root user 

It does not matter. The command is configured to accept both types of users.

**Comment by SDRausty** [comment]
This command was part of the default installation for a little while after it was created.  The reason it was dropped from the default install process is that it wants python (~10MB).

**Comment by JanuszChmiel** [comment]
No problem.
I will be very glad to try The command.
Orca is programmed in Python too so no problem, that some process will also
require Python interpreter.

**Comment by JanuszChmiel** [comment]
Really. Systemctl allow us to run ArchLinux services. I will try to type
systemctl run dbus
before I will run Tigervnc and mate-session to see The results.
Because I think, that system bus if there is so kind of service it will
require kernel modules to communicate with real system bus so it would not
make too much sense to load system bus related service in Termux on Android
device.
Thank you that you have included such command.
I Am thinkink, which userspace related services names should be loaded.
Sure, none of them which require real Linux kernel to work or which require
to communicate with real hardware.

**Comment by JanuszChmiel** [comment]
Oh. Simply run dbus service do not help. What will happen if I will manually
create The cosket file in The needed directory? It will be ineresting what
will happen.

**Comment by JanuszChmiel** [comment]
When I simply type
systemctl
Does this comman automatically load all loadable services? Or it will only
list The list of available services, which must be manually loaded by typing
systemctl run servicename

**Comment by JanuszChmiel** [comment]
Oh I Am very sorry. I must type
systemctl start servicename
no run

**Comment by saefanms** [comment]
Hello World

**Comment by JanuszChmiel** [comment]
Unfortunately, as I can see, this problem can not be simply solved so The
best what I can do is to simply ignore it.
LXDE desktop do not require this type of connection as mate-session. But
Mate desktop is much more accessible.

**Comment by SDRausty** [comment]
@JanuszChmiel you asked a number of very interesting questions; Please try https://github.com/gdraheim/docker-systemctl-replacement/issues to see if answers can be found at the main site for the systemctl Android PRoot replacement we are using.
