### ISSUE TITLE
makeyay does not work correctly via wifi

### ISSUE THREAD

**Issue by xd003** [TermuxArch/TermuxArch#33]
I just did a fresh install of Termuxarch latest v2.0.568 , created a user . After logging in as user , i am trying to run makeyay but it always exits installer with some errors. Here's the full output
```
❯ ./makeyay
Building and installing 'yay':
When this message:
libtool: warning: remember to run 'libtool --finish /usr/lib/libfakeroot'
When this message is displayed on the screen 'makeyay' will deal with it a little bit later in the build proccess, and there will be a short pause when this message is displayed:
"Libraries have been installed in:"
A difficult part of any build process can be choosing the correct answers.  Here are the correct answers:
:: fakeroot-tcp and fakeroot are in conflict. Remove fakeroot? [y/N] y
Tap the 'y' key first, then enter.  For the first question, the 'y' key must be tapped first, then enter.  Yes will be chosen when enter is tapped in all of the questions after the first question:
:: Proceed with installation? [Y/n]
Tap enter once more as this build proccess continues.  If everything goes well, you will see these messages:
Libraries have been installed in:
The message above will be displayed for a short time with more information.  Then setupTermuxArch will go on, and there will be one more tap enter yo touch before script setupTermuxArch is done;  SLEEPING SIX SECONDS...
sleep 6
makefakeroottcp  2.0.476: DONE 🏁
Then this pocess will go on to try to make 'yay' which is much simpler for the user;  There is no tapping yes enter needed to be done whatsoever.
./makeyay: line 75: patchmakepkg: command not found
./makeyay: line 16: patchmakepkg: command not found

 TermuxArch WARNING:  Generated script signal 127 near or at line number 75 by !

makeyay  2.0.568 [Exit Signal 201]: DONE  🏁
```

Android 10 , arm64-v8 ( aarch64)

**Comment by SDRausty** [comment]
Thanks for sharing insight about the project @xd003.  Hence I am retesting a number of install methods on Android 9/10 armv7l, including intranet and directly networked installs.  I have ran into this error on an intranet connection which was NOT present before:

```
Trailers or upgrade present.
Couldn't parse server headers
```

The direct internet connection reinstall and `makeyay` command is progressing as expected:
```
resolving dependencies...
looking for conflicting packages...
:: fakeroot-tcp and fakeroot are in conflict. Remove fakeroot? [y/N] y
```
```
(1/1) Arming ConditionNeedsUpdate...                                          
Building and installing fakeroot-tcp: DONE 🏁
makefakeroottcp  2.0.568: DONE 🏁                                             
Cloning into 'yay'...
```
This command completed building `yay` successfully.  Is the install process that you mentioned connected directly to the internet or through an intranet?

**Comment by SDRausty** [comment]
There intranet reinstall and `makeyay` command exited with this error:
```
curl: (22) The requested URL returned error: 502 Couldn't parse server headers
Warning: Transient problem: HTTP error Will retry in 3 seconds. 1 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502 Couldn't parse server headers
==> ERROR: Failure while downloading http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.24.orig.tar.gz
    Aborting...

 TermuxArch WARNING:  Generated script signal 201 near or at line number 76 by Building and installing fakeroot-tcp:
Continuing to build and install fakeroot-tcp:
==> Making package: fakeroot-tcp 1.24-2 (Thu 17 Sep 2020 02:00:39 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading fakeroot_1.24.orig.tar.gz...

 TermuxArch WARNING:  Generated script signal 1 near or at line number 59 by ==> Making package: fakeroot-tcp 1.24-2 (Thu 17 Sep 2020 02:01:02 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading fakeroot_1.24.orig.tar.gz...!

makefakeroottcp  2.0.568 [Exit Signal 201]: DONE  🏁
!

makeyay  2.0.568 [Exit Signal 201]: DONE  🏁
```

The next to last line is similar to yours.

**Comment by xd003** [comment]
> This command completed building `yay` successfully.  Is the install process that you mentioned connected directly to the internet or through an intranet?

It i connected directly to the internet through a wifi

**Comment by xd003** [comment]
Well , I just tried ./makeyay using my mobile data and got the same error 

In the title , do you mean to conclude - makeyay not working if Termuxarch is installed while connected to the internet through wifi ?

**Comment by SDRausty** [comment]
```
patchmakepkg
Attempting to patch makepkg:
Already patched makepkg: DONE 🏁
patchmakepkg  2.0.294: DONE 🏁
```
> In the title , do you mean to conclude - `makeyay is not working if Termuxarch is installed while connected to the internet through wifi`?

As far as I can tell there are no errors when directly connected to the Internet.

**Comment by SDRausty** [comment]
@xd003 what is the result of `export` in Arch Linux?

**Comment by xd003** [comment]
> @xd003 what is the result of `export` in Arch Linux?

```
HOME=/home/xd003
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LESS=-R
LOGNAME=xd003
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
OLDPWD=/home/xd003
P9K_SSH=0
P9K_TTY=old
PAGER=less
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PWD=/home/xd003
SHELL=/bin/zsh
SHLVL=1
TERM=xterm-256color
USER=xd003
ZSH=/home/xd003/.oh-my-zsh
```

**Comment by SDRausty** [comment]
> result of `export` in Arch Linux?

The reason I am asking you to share your exports is there appear to be different behaviors of command `makeyay` depending on the route and configuration.  For example, this error crops up at times when Arch Linux in PRoot is not directly connected to the Internet:
`curl: (22) The requested URL returned error: 502 Couldn't parse server headers                            Warning: Transient problem: HTTP error Will retry in 3 seconds. 1 retries                                 Warning: left.                                                                                              0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                            curl: (22) The requested URL returned error: 502 Couldn't parse server headers                            ==> ERROR: Failure while downloading http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.24.orig.tar.gz
    Aborting...`

Another error also occurs when Arch Linux in QEMU PRoot is directly connected to the Internet is:
`sudo: /etc/sudo.conf is owned by uid 1001, should be 0
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set`

**Comment by SDRausty** [comment]
@xd003 thank you for sharing exports.

**Comment by SDRausty** [comment]
```
==> Installing package yay with pacman -U...
loading packages...
warning: yay-10.0.4-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) yay-10.0.4-1

Total Installed Size:  7.32 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                  [###################################] 100%
(1/1) checking package integrity                                [###################################] 100%
(1/1) loading package files                                     [###################################] 100%
(1/1) checking for file conflicts                               [###################################] 100%
:: Processing package changes...
(1/1) reinstalling yay                                          [###################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Paths that can be followed after building 'yay' are 'yay cmatrix' which builds matrix screensavers.  The commands 'yay pikaur|pikaur-git|tpac' build more aur installers which can also be used to download aur repositories and build packages like with 'yay' in your Android smartphone, tablet, wearable and more.  Did you know that 'android-studio' is available with the command 'yay android'?
If you have trouble importing keys, this command 'gpg --keyserver keyserver.ubuntu.com --recv-keys 71A1D0EFCFEB6281FD0437C71A1D0EFCFEB6281F' might help.  Change the number to the number of the key being imported.
Building and installing yay: DONE 🏁
makeyay  2.0.576: DONE 🏁
```

**Comment by xd003** [comment]
Looks good , Should i now proceed to reinstall Termuxarch and test test makeyay over wifi or some more changes are remaining to be pushed ?

**Comment by SDRausty** [comment]
The two errors in comment https://github.com/TermuxArch/TermuxArch/issues/33#issuecomment-699452334_ might be related as both may stem from permissions.  This command might help in resolving this issue:
```
$ f sudoers *h
archlinuxconfig.bash:30:                        sed -i "/# %wheel ALL=(ALL) NOPASSWD: ALL/ s/^# *//" /etcsudoers                                                                                                    
archlinuxconfig.bash:31:                        sed -i "/# ALL ALL=(ALL) ALL/ s/^# *//" /etc/sudoers      
archlinuxconfig.bash:32:                        sed -i "s/# ALL ALL=(ALL) ALL/ALL ALL=(ALL) NOPASSWD: ALL/g" /etc/sudoers                                                                                           
archlinuxconfig.bash:33:                        grep -q 'ftp_proxy' /etc/sudoers && : || echo 'Defaults env_keep += "ftp_proxy http_proxy https_proxy"' >> /etc/sudoers                                             
archlinuxconfig.bash:43:        #               [[ -d /etc/sudoers.d ]] && printf "%s\\\\n" "\$1 ALL=(ALL) ALL" >> /etc/sudoers.d/"\$1"
```

**Comment by SDRausty** [comment]
Function `_PR00TSTRING_` in file [knownconfigurations.bash](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash) might also help in resolving this issue.

**Comment by SDRausty** [comment]
> reinstall Termuxarch and test test makeyay over wifi 

There should not be any need to reinstall.  Refreshing the installation with `setupTermuxArch refresh` should be sufficient.  It probably will not work over wifi in its' present state, and of course you can test.  If you are getting permission errors, please research and share them.  I have spent many hours trying to resolve the permission errors.

**Comment by SDRausty** [comment]
> many hours (days) trying to resolve

One of the fascinating things I found during testing about Intranets is that there are many configuration options. I found no working resolutions.  Which I am sure are present, just not found at the moment.

> I am mentioning it because I had tried very same version of Termuxarch on very same device with same wifi internet few hours prior to reporting this issue and haven't faced any issue with makeyay

Found it fascinating you're mentioning this because I **found no problems with the intranet** too, and then the next morning @xd003  you were kind enough to share this issue.

**Comment by SDRausty** [comment]
> reinstall

There is always a want to reinstall when testing the install process.  Thank you for helping with this task.  This command `setupTermuxArch i customdir` can be called to assist in the task of testing the install process:

`[i[nstall] [customdir]]  Install Arch Linux in a custom directory.  Instructions: Install in userspace.  The HOME directory is appended to the installation directory.  To install Arch Linux in HOME/customdir use 'bash setupTermuxArch install customdir'.  In the BASH shell you can use './setupTermuxArch install customdir'.  All options can be abbreviated to one, two and three letters.  Hence './setupTermuxArch install customdir' can be run as 'setupTermuxArch i customdir' in BASH.`

The newly implemented command `setupTermuxArch q i customdir` can also be summond to help resolve this issue:

`[q[emu] [customdir]]  Partial Implementation:  Install alternate architecture on smartphone with QEMU.`

The command `setupTermuxArch h` has more  information.  If space is not an issue on smartphone it may be possible to **run all concurrent architectures for testing this issue** and this [one](https://github.com/TermuxArch/TermuxArch/issues/33) too.

**Comment by SDRausty** [comment]
This [TermuxArch version 2.0.579 release](https://github.com/TermuxArch/TermuxArch/releases/tag/2.0.579) does not manifest any errors through a direct wifi connection.  Enjoy and please share your experience with  Linux in your phone!

**Comment by SDRausty** [comment]
If there are errors over a wifi proxy connection, please try switching to a different proxy.  Switching proxies might be the simplest solution in the case of wifi proxy connections.

**Comment by SDRausty** [comment]
> there are many configuration options. 

If there are errors over a wifi proxy connection with `makeyay`, please try a different proxy.  Switching proxies might be the simplest solution if encountering errors with `makeyay` over a wifi connections that use a proxy.

**Comment by xd003** [comment]
> This [TermuxArch version 2.0.579 release](https://github.com/TermuxArch/TermuxArch/releases/tag/2.0.579) does not manifest any errors through a direct wifi connection with the Internet.  Enjoy and please share your experience with Arch Linux in Termux PRoot in your smartphone!

Can confirm thi
Tested Latest Termuxarch version over a non proxied wifi network , didn't got any issues with yay
Cheers

**Comment by SDRausty** [comment]
Thank you for confirming.  One of the remaining mysteries of this issue is why proxies behave erratically on smartphones.  Sometimes they work very well.  Othertimes they appear to cause unpredictable errors.

**Comment by SDRausty** [comment]
How are your results with 127.0.0.1 localnet?  I have noticed that there are differences between using localnet and 192.168.0.0 privatenet.  Have you?

**Comment by SDRausty** [comment]
@xd003 as these commands `makeyay && yay pikaur && pikaur cmatrix` appear to have difficulty functioning as expected, this issue is reopened.  Testing is requested.  

Note:  Please note when testing on a standalone unit, please back your work up your work before continuing.

**Comment by xd003** [comment]
@SDRausty 
I did noticed just now that you had re-opened 2 closed issues and need help with testing .My device was formatted recently hence i was reinstalling Termuxarch in manual mode but it is always failing and returns an error

**Comment by xd003** [comment]
@SDRausty attempted to test makeyay in the latest Termuxarch . Here's the whole output 
```
[0;32mBuilding and installing 'yay':[0m
When this message:
libtool: warning: remember to run 'libtool --finish /usr/lib/libfakeroot'
When this message is displayed on the screen 'makeyay' will deal with it a little bit later in the build proccess, and there will be a short pause when this message is displayed:
"Libraries have been installed in:"
A difficult part of any build process can be choosing the correct answers.  Here are the correct answers:
:: fakeroot-tcp and fakeroot are in conflict. Remove fakeroot? [y/N] y
Tap the 'y' key first, then enter.  For the first question, the 'y' key must be tapped first, then enter.  Yes will be chosen when enter is tapped in all of the questions after the first question:
:: Proceed with installation? [Y/n]
Tap enter twice more as this build proccess continues.  If everything goes well, you will see these messages:
Libraries have been installed in:
The message above will be displayed for a short time with more information.  Then setupTermuxArch will go on, and there will be one more tap enter to touch before script setupTermuxArch is done;  SLEEPING SIX SECONDS...
makefakeroottcp 2.0.821: DONE 🏁
Then this process will go on to try to make 'yay' which is much simpler for the user;  There is no tapping yes enter needed to be done whatsoever.
/home/xd003/bin/makeyay: line 76: fakeroot: command not found
Building and installing fakeroot-tcp: 

[1;32m==> [1;37mRunning [1;32mTermuxArch pci automake base-devel fakeroot git gcc po4a libtool 2.0.821 [0m...
[1;34m::[0;1m Synchronizing package databases...
[0mdownloading core.db...
downloading extra.db...
downloading community.db...
downloading alarm.db...
downloading aur.db...
[1;34m::[0;1m There are 24 members in group [1;34mbase-devel[0;1m:
[0m[1;34m::[0;1m Repository [1;35mcore
[0m[0;1m  [0m 1) autoconf  2) automake  3) binutils  4) bison  5) fakeroot  6) file  7) findutils  8) flex  9) gawk  10) gcc  11) gettext  12) grep  13) groff  14) gzip  15) libtool  16) m4  17) make  18) pacman  19) patch  20) pkgconf  21) sed  22) sudo  23) texinfo  24) which

Enter a selection (default=all): [1;33mwarning: [0mfile-5.39-1 is up to date -- reinstalling
[1;33mwarning: [0mfindutils-4.7.0-2 is up to date -- reinstalling
[1;33mwarning: [0mgawk-5.1.0-1 is up to date -- reinstalling
[1;33mwarning: [0mgettext-0.21-1 is up to date -- reinstalling
[1;33mwarning: [0mgrep-3.5-1 is up to date -- reinstalling
[1;33mwarning: [0mgzip-1.10-3 is up to date -- reinstalling
[1;33mwarning: [0mpacman-5.2.2-1 is up to date -- reinstalling
[1;33mwarning: [0mpatch-2.7.6-8 is up to date -- reinstalling
[1;33mwarning: [0msed-4.8-1 is up to date -- reinstalling
[1;33mwarning: [0msudo-1.9.3.p1-1 is up to date -- reinstalling
[1;33mwarning: [0mwhich-2.21-5 is up to date -- reinstalling

[1;34m::[0;1m Starting full system upgrade...
[0mresolving dependencies...
looking for conflicting packages...

[0;1mPackages (39)[0m elfutils-0.181-1  gc-8.0.4-4  guile-2.2.6-2  libdatrie-0.2.12-2  libmicrohttpd-0.9.71-1  libmpc-1.1.0-2  libthai-0.1.28-2  perl-error-0.17029-2  perl-mailtools-2.21-4  perl-mime-charset-1.012.2-7  perl-timedate-2.33-2  perl-unicode-linebreak-2019.001-3  perl-yaml-tiny-1.73-4  autoconf-2.69-7  automake-1.16.2-3  binutils-2.35-1  bison-3.7.2-1  fakeroot-1.25.3-1  file-5.39-1  findutils-4.7.0-2  flex-2.6.4-3  gawk-5.1.0-1  gcc-10.2.0-1  gettext-0.21-1  git-2.29.2-1  grep-3.5-1  groff-1.22.4-3  gzip-1.10-3  libtool-2.4.6+44+gb9b44533-14  m4-1.4.18-3  make-4.3-3  pacman-5.2.2-1  patch-2.7.6-8  pkgconf-1.7.3-1  po4a-0.61-2  sed-4.8-1  sudo-1.9.3.p1-1  texinfo-6.7-3  which-2.21-5

[0;1mTotal Download Size: [0m   58.76 MiB
[0;1mTotal Installed Size:[0m  301.53 MiB
[0;1mNet Upgrade Size:    [0m  272.45 MiB

[1;34m::[0;1m Proceed with installation? [Y/n] [0m
[1;34m::[0;1m Retrieving packages...
[0mdownloading automake-1.16.2-3-any.pkg.tar.xz...
downloading gawk-5.1.0-1-aarch64.pkg.tar.xz...
downloading m4-1.4.18-3-aarch64.pkg.tar.xz...
downloading autoconf-2.69-7-any.pkg.tar.xz...
downloading libmicrohttpd-0.9.71-1-aarch64.pkg.tar.xz...
downloading findutils-4.7.0-2-aarch64.pkg.tar.xz...
downloading elfutils-0.181-1-aarch64.pkg.tar.xz...
downloading binutils-2.35-1-aarch64.pkg.tar.xz...
downloading bison-3.7.2-1-aarch64.pkg.tar.xz...
downloading sed-4.8-1-aarch64.pkg.tar.xz...
downloading file-5.39-1-aarch64.pkg.tar.xz...
downloading fakeroot-1.25.3-1-aarch64.pkg.tar.xz...
downloading flex-2.6.4-3-aarch64.pkg.tar.xz...
downloading libmpc-1.1.0-2-aarch64.pkg.tar.xz...
downloading gcc-10.2.0-1-aarch64.pkg.tar.xz...
downloading groff-1.22.4-3-aarch64.pkg.tar.xz...
downloading gzip-1.10-3-aarch64.pkg.tar.xz...
downloading libtool-2.4.6+44+gb9b44533-14-aarch64.pkg.tar.xz...
downloading texinfo-6.7-3-aarch64.pkg.tar.xz...
downloading make-4.3-3-aarch64.pkg.tar.xz...
downloading pacman-5.2.2-1-aarch64.pkg.tar.xz...
downloading pkgconf-1.7.3-1-aarch64.pkg.tar.xz...
downloading which-2.21-5-aarch64.pkg.tar.xz...
downloading gc-8.0.4-4-aarch64.pkg.tar.xz...
downloading guile-2.2.6-2-aarch64.pkg.tar.xz...
downloading perl-error-0.17029-2-any.pkg.tar.xz...
downloading perl-timedate-2.33-2-any.pkg.tar.xz...
downloading perl-mailtools-2.21-4-any.pkg.tar.xz...
downloading git-2.29.2-1-aarch64.pkg.tar.xz...
downloading perl-mime-charset-1.012.2-7-any.pkg.tar.xz...
downloading libdatrie-0.2.12-2-aarch64.pkg.tar.xz...
downloading libthai-0.1.28-2-aarch64.pkg.tar.xz...
downloading perl-unicode-linebreak-2019.001-3-aarch64.pkg.tar.xz...
downloading perl-yaml-tiny-1.73-4-any.pkg.tar.xz...
downloading po4a-0.61-2-any.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
[1;34m::[0;1m Processing package changes...
[0minstalling automake...
reinstalling gawk...
installing m4...
installing autoconf...
installing libmicrohttpd...
reinstalling findutils...
installing elfutils...
installing binutils...
installing bison...
reinstalling sed...
reinstalling file...
installing fakeroot...
installing flex...
installing libmpc...
installing gcc...
reinstalling gettext...
reinstalling grep...
installing groff...
Optional dependencies for groff
[0;1m   [0m netpbm: for use together with man -H command interaction in browsers
    psutils: for use together with man -H command interaction in browsers
    libxaw: for gxditview
    perl-file-homedir: for use with glilypond
reinstalling gzip...
installing libtool...
installing texinfo...
installing gc...
installing guile...
installing make...
reinstalling pacman...
reinstalling patch...
installing pkgconf...
reinstalling sudo...
reinstalling which...
installing perl-error...
installing perl-timedate...
installing perl-mailtools...
installing git...
Optional dependencies for git
[0;1m   [0m tk: gitk and git gui
    perl-libwww: git svn
    perl-term-readkey: git svn and interactive.singlekey setting
    perl-mime-tools: git send-email
    perl-net-smtp-ssl: git send-email TLS support
    perl-authen-sasl: git send-email TLS support
    perl-mediawiki-api: git mediawiki support
    perl-datetime-format-iso8601: git mediawiki support
    perl-lwp-protocol-https: git mediawiki https support
    perl-cgi: gitweb (web interface) support
    python: git svn & git p4 [installed]
    subversion: git svn
    org.freedesktop.secrets: keyring credential helper
    libsecret: libsecret credential helper [installed]
installing perl-yaml-tiny...
installing perl-mime-charset...
installing libdatrie...
installing libthai...
installing perl-unicode-linebreak...
installing po4a...
[1;34m::[0;1m Running post-transaction hooks...
[0m(1/6) Creating system user accounts...
Creating group git with gid 976.
Creating user git (git daemon user) with uid 976 and gid 976.
(2/6) Reloading system manager configuration...
  Skipped: Current root is not booted.
(3/6) Creating temporary files...
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
(4/6) Arming ConditionNeedsUpdate...
(5/6) Warn about old perl modules
(6/6) Updating the info directory file...
[?25h[0m[0;32mTermuxArch pci automake base-devel fakeroot git gcc po4a libtool 2.0.821[1;34m: [1;32mDONE 📱[0m 🏁  

[0m]2;  🔑 TermuxArch pci automake base-devel fakeroot git gcc po4a libtool:DONE 📱 Cloning into 'fakeroot-tcp'...
==> Making package: fakeroot-tcp 1.24-2 (Tue 10 Nov 2020 03:34:26 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading fakeroot_1.24.orig.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.24.orig.tar.gz
    Aborting...
Continuing to build and install fakeroot-tcp: 
==> Making package: fakeroot-tcp 1.24-2 (Tue 10 Nov 2020 03:34:56 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading fakeroot_1.24.orig.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.24.orig.tar.gz
    Aborting...
[?25h
[1;48;5;138m TermuxArch WARNING:  Generated script signal 1 near or at line number 59 by 'makepkg -irs'![0m

[0;32mmakefakeroottcp  2.0.821 [0m[Exit Signal 201][1;34m: [1;32mDONE  🏁 [0m
[0m]2; makefakeroottcp : [Exit Signal 201] DONE 🏁  [?25h[0m[?25h
[1;48;5;138m TermuxArch WARNING:  Generated script signal 201 near or at line number 76 by 'makefakeroottcp'![0m

[0;32mmakeyay  2.0.821 [0m[Exit Signal 201][1;34m: [1;32mDONE  🏁 [0m
[0m]2; makeyay : [Exit Signal 201] DONE 🏁  [?25h[0m
```

**Comment by SDRausty** [comment]
Thank you for sharing;  It appears upstream is gone.  I'm not sure what to do to resolve this.  I shared our success at https://www.reddit.com/r/archlinux/comments/iqbjvw/wow_yay_works_in_my_android_smartphone/ and this share was locked and taken down, "Such gross and blatant clickbait on this sub ? Am I the only one to feel that this post should be moderated, at least as is ?"  

![Screenshot_20201110-090705](https://user-images.githubusercontent.com/27742457/98685005-dabca600-2334-11eb-9ec9-9dc5c7e2d40a.png)
![Screenshot_20201110-090723](https://user-images.githubusercontent.com/27742457/98685162-08095400-2335-11eb-9b6c-27975a512550.png)


Since it appears that upstream is gone, I mailed the authors of https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fakeroot-tcp and am awaiting a reply.  What is your opinion about this turn of events?

**Comment by xd003** [comment]
@SDRausty 
After some efforts ,i got the fakeroot tcp files hosted here , it even has a newer version than the one we were using ( ie 1.24 ) 
Main Index Page - http://http.kali.org/kali/pool/main/f/fakeroot/

This is a direct link to the file we were using earlier - http://http.kali.org/kali/pool/main/f/fakeroot/fakeroot_1.24.orig.tar.gz
Here's a supposedly newer version from the same page - http://http.kali.org/kali/pool/main/f/fakeroot/fakeroot_1.25.3.orig.tar.gz

Hopefully this will help : )

**Comment by SDRausty** [comment]
Thank you for your time and share @xd003. This is what I propose to resolve this issue:

1. We are already building amazing creations on Android smartphones,
1. **Where is the source code for the package we are missing?**
1. My suggestion is to proceed with this quest similar to what command 'csystemctl' does in TermuxArch, which is to include the build tools we already are using anyway and to build 'fakeroot-tpc` from source into package on device to attempt to resolve this topic.

Do you agree with this proposed solution?

**Comment by xd003** [comment]
@SDRausty 
Yes 100% agreed. Also the size of the fakeroot file is quite low. Would be good to have it ship with Termuxarch itself and fetch the file easily while running makeyay without depending on any external source

**Comment by SDRausty** [comment]
Thank you for expressing your opinion @xd003; These are two possible alternatives:

1. Do you know a good article about how to create an Arch Linux package from source?
1. Should fakeroot-tcp be installed directly from source?

Which do you prefer?

**Comment by xd003** [comment]
@SDRausty 

1) https://www.vultr.com/docs/building-packages-on-arch-linux
This one is a good article which shows how do we make a arch package . We basically have to just create a .PKGFILE for our package .

2) Creating and shipping a  prebuilt binary/package will help us to save on the compiling time for all users .So the process will get completed comparatively quickly as opposed to directly installing from source

**Comment by SDRausty** [comment]
This issue is now closed as creating `fakeroot-tcp` is no longer required.  The error in `makeyay` over wifi was being generated when attempting to make the `fakeroot-tcp` prerequisite package.  The newly created and recently added `proot` option [`--sysvipc`](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L91) resolves the underlying error in `fakeroot` that called for the manifestation of the `fakeroot-tcp` package.

**Comment by JanuszChmiel** [comment]
Yes, Makeyay now rork perfectly. Proot update has solved this issue and it is very very good programmers work of Proot team members.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz
