### ISSUE TITLE
fakeroot version 24 is no longer available

### ISSUE THREAD

**Issue by dansteen** [TermuxArch/TermuxArch#37]
the makefakeroot script (and associated package) tries to pull version 24.1 from the debian repository, however, that version is no longer available.   There is a version 25 available, however, that version no longer needs the silence-dlerror.patch file since it's already included.

**Comment by SDRausty** [comment]
> version no longer needs the silence-dlerror.patch file since it's already included.

Thank you for sharing this information.  Do you know where the source is for fakeroot-tcp?

**Comment by dansteen** [comment]
the package build pulls it from here: 
 http://ftp.debian.org/debian/pool/main/f/fakeroot/

**Comment by SDRausty** [comment]
@dansteen thank you for this link; For some unknown reason I was having difficulty reaching it.

**Comment by SDRausty** [comment]
> unknown reason I was having difficulty reaching it.

I just rechecked on the device that is still generating this unknown difficulty; `The following error occurred while trying to access http://ftp.debian.org/debian/pool/main/:
502 Couldn't parse server headers`

I want check this smartphone's configuration after confirming this error.  Back to the task at hand:

> Would be good to have it ship with Termuxarch itself and fetch the file easily while running makeyay without depending on any external source

_Originally posted by @xd003 in https://github.com/TermuxArch/TermuxArch/issues/33#issuecomment-725808512_

These are two possible alternatives:
1. Do you know a good article about how to create an Arch Linux package from source?
1. Should `fakeroot-tcp` be installed directly from source?

Which do you prefer @dansteen?

**Comment by SDRausty** [comment]
After analizing the 502 error a little more, it appears to be related to [makeyay does not work correctly via wifi #33](#33).

**Comment by dansteen** [comment]
HI @SDRausty ,

Thanks for looking into this!

The wifi issue is interesting.  I was not on wifi when I set things up so I can't speak to that.

However, building a package from source for arch is super easy.  The basics are here:   ```https://wiki.archlinux.org/index.php/Makepkg#Usage```
But what it comes down to is:

```
cd <dir containing your PKGBUILD file>
makepkg -sr
```
and that's it!

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/daee4ab090449e518509444e737075a2e8ba3ffe commit resolves the immediate want to find a replacement for fakeroot version 24.  Thank you @dansteen for sharing important details about this issue.

**Comment by SDRausty** [comment]
This issue is now closed as creating `fakeroot-tcp` is no longer required.  The newly created and recently added `proot` option [`--sysvipc`](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L91) resolves the underlying error in `fakeroot` that called for the manifestation of the `fakeroot-tcp` package.
