### ISSUE TITLE
public apologisation addressed to MR Rausty

### ISSUE THREAD

**Issue by JanuszChmiel** [TermuxArch/TermuxArch#39]
Dear MR Rausty,
I would like to publicly apologize you that I have overloaded you with many opened issues and I Am aware, that I have made many errors including. I have opened several issues for A same topics. I have overloaded you with making more and more desktop environments to work from chroot environment. And I have overloaded you. I Am offering you a more nice approach from you for a following days and months.
I will finally stop opening accessibility related issues, I will always try to solve them with The corresponding packages authors. Because I know, that you can not solve 1000thinks at The same time.
If you will need help to test something, please let Me know on A corresponding issue which you will open. Or in A corresponding commit.
I Am ery sorry again and I Am also publicly apologizing all available users and members here for my wrong behaviour and approach to MRS Rausty complex work.

**Comment by SDRausty** [comment]
Your apology is whole heartedly accepted @JanuszChmiel;  please do not be sorry for pursuing your dream.  

> issue ... open

Whether or not an issue is open or closed should not affect the ability to comment at a particular issue unless an issue is locked.

> accessibility related issues

One of my goals when I started these projects years ago was simply to have them work as expected with relative ease.  I believe we have made tremendous progress related to this goal and to a newer goal of accessibility in general with this work.  These improvements have trickled down to enhance the end-user experience.  I hope that you agree.

**Comment by JanuszChmiel** [comment]
I Am very glad, that you have accepted my apologisation. Yes, I agree with you. I have also found realisticuse of yours professional scripts and Arch Linux.
It is a opportunity to code A WEB pages by using Pas2js and Lazarus.
I hsave also come in to conclusion, that desktop environments are unnecessary breaks to a task on Android phones and Termux. I can simply use light weight window managers such as ratpoison and I can add various hot keys. I can even switch between Windows. So instead of spending plenty of time to test GNome, Mate, LXDE and others, I will be rather use ratpoison or ismilar window manager instead.

I will save RAM, CPU resources and my resulting users experience will be even better.
I have also found a wonderful daily work for myself. It is development of simple interactive WEB forms with A nice tables and with useful quizes for people from our country. Especially for seniors.
Because I have studied psychology, I have found Pas2js and some special units very inspirative to create various word based interactive forms. The most  inspirative advantage of Pas2js is its ability to directly compile to Javascript. The advantage of many of available opensource units is The possibility to code nice WEB apps with no need to specify every object position values. In Lazarus FPC, I would had to create .lfm file first, I would had to manuály fill out GUI elements and I could change its positions on A run time inside .pas code. The disadvantage of this approach is The fact, that I can not use form designer and using more than one file can make Me lost inside coding.
Pas2js contain special WEBwidgets, which are capable to create even nice tables and many GUi WEB based elements. I will be able to use Lazarus and Pas2js even on The phone and I will be able to test my WEB interactive applications on Android or by using Orca screen reader and Firefox WEB browser.
Fortunately for Me, pas2js community is full of kind people and MR Wancare has shown Me a way how to develop by using Pas2js.
WEB apps is The future of programming. Sure. I will not use pictures, but I will only use word based quizes. Pas2js support special coding, which dynamically monitor even 25 or more editable boxes at The same time. User do not have to even press Enter or click on some item to confirm some value. 
And MR Wancare and others are Javascript and Pascal elite developers so They také care about hydden differences among WEB browsers, so resulting code work with several browser and even or Android or Mac.
And I Am not lazy, so I will build Pas2js and Lazarus myself because I have done it also for Windows without problems.
I will be patiently waiting, since something wrong have happened with ArchLinux setup scripts. I can not finish installation till The end. I have been afraid, that it was caused by Android kernel update, but Debian work so it must be some other repositoryes problém.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
> since something wrong have happened with ArchLinux setup scripts

This appears to be a newly arisen error with QEMU support.  I have opened an issue at https://github.com/termux/termux-packages/issues/6141 entitled "qemu-user-i386 error #6141".  Hopefully a solution will be found soon.

**Comment by JanuszChmiel** [comment]
Thank you very very much. Script crash even if I do not type visual option. I have been afraid, that kernel update from July 2020, which Huavei have prepared for my model several years ago have caused this problém. So as a confirmation of my assumption, I have used Proot-distro scripts to install Debian. Because apt install task-mate-desktop did n ot caused crashes and because mate-session and Orca have worked, with no issues, I have found out, that Proot should not have troubles.
I have beern afraid, that Huavei Kernel developers will add special obstructions for Termux and Proot users, which will prevent it from working. FOrtunately for Me no.
Termux and Linux on Android device is one of my big joy.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
> Script crash even if I do not type visual option. 

I have noticed the script crashing when using QEMU with PRoot after updating Termux packages, so I opened an issue https://github.com/termux/termux-packages/issues/6141 at Termux packages regarding this new development.

**Comment by SDRausty** [comment]
> Script crash even if I do not type visual option.

Can you please post the output from the crash without using the visual option?

**Comment by JanuszChmiel** [comment]
Of course, here is The output before script download bootstrap big file with file systém.

~ $ ./setupTermuxArch.bash

 đź•› > đź•› ďĽ´ď˝…ď˝’ď˝Ťď˝•ď˝ďĽˇď˝’ď˝ď˝ 2.0.950 will attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot will be available upon successful completion.  To run this BASH script again, use '!!'.  Ensure background data is not restricted.  Check the wireless connection if you do not see one o'clock đź• below.  Checking prerequisites...

Found download tool 'wget': Continuing...

Using wget to manage downloads.

 đź•› > đź•§ Prerequisites: OK  Downloading TermuxArch...

setupTermuxArch.sha 100%[===================>]     153  --.-KB/s    in 0.001s
setupTermuxArch.tar 100%[===================>]  74.64K  --.-KB/s    in 0.04s

 đź•› > đź• TermuxArch download: OK


 đź•› > đź•ś TermuxArch 2.0.950 integrity: OK
knownconfigurations.bash: line 87: [[: 8.0.0: syntax error: invalid arithmetic operator (error token is ".0.0")
Creating directory '/etc'.
Creating directory '/home'.
Creating directory '/root/bin'.
Creating directory '/usr/bin'.
Creating directory '/usr/local/bin'.
Creating directory '/var/backups/arch/etc'.
Creating directory '/var/backups/arch/root'.
Creating directory '/var/binds'.
Setting locales to: Language >> cs_CZ << Region: Please wait a moment.
line '(setq visible-bell 1)' can not be found in /arch/root/.emacs file : adding line '(setq visible-bell 1)' to /arch/root/.emacs file
line 'set belloff=all' can not be found in /arch/root/.vimrc file : adding line 'set belloff=all' to /arch/root/.vimrc file
Adjusting ownership and permissions...

 đź•› > đź•¦ File startarch copied to /data/data/com.termux/files/usr/bin.

 đź•› > đź•ť Detected Android arm64-v8a 8.0.0 operating system;  Install architecture is set to arm64-v8a.

 đź•› > đź•’ Activating termux-wake-lock: DONE

 đź•› > đź•ž Contacting worldwide mirror https://os.archlinuxarm.org: DONE

 đź•› > đź•“ Downloading the checksum file and ArchLinuxARM-aarch64-latest.tar.gz from the geographically local mirror http://hu.mirror.archlinuxarm.org/.  If contact with the local mirror is not successful, run bash setupTermuxArch.bash again.  Should the worldwide mirror not provide another geographically nearby server after a couple of attempts, use bash setupTermuxArch.bash manual after locating a local mirror from the Internet; The command bash setupTermuxArch.bash help has information about additional options.  Download of ArchLinuxARM-aarch64-latest.tar.gz pending Internet connection...

ArchLinuxARM-aarch6 100%[===================>]      69  --.-KB/s    in 0s
-aarch64-latest.tar  15%[==>                 ]  86.26M  3.81MB/s    eta 2m 27s


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
Scripts have caused this chaos after Huavei kernel upgrade. So may be, that there is really something wrong after update. I will try on Android 6.0 if Termux repos are working for 6.0 and if there will not be rrrors and yours script will work ammazingly like before including CZUTF8 localisation routine, it will be really unsoft hydden error related to kernel upgrade.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
When ArchLinux tar file is being extracted by using Proot, I Am getting The following, may be not remarkable error.

usr/bin/newgidmap: Cannot restore extended attributes on this systém

May be, that this is some hydden problém after update.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
> usr/bin/newgidmap: Cannot restore extended attributes on this systém

Thank you for sharing information about these new errors.  This https://github.com/TermuxArch/TermuxArch/commit/da72652da4967e6ccdb64e5ff051c4c238852d9c commit alleviates the extended attributes error which caused the script to crash. 

> May be, that this is some hydden problém after update.

I agree. This error arose after updating Termux packages.  Please ensure that you are also using the latest version of Termux app as both app and packages should be up-to-date.

**Comment by SDRausty** [comment]
> Scripts have caused this chaos after Huavei kernel upgrade. 

The Androids that I am using are not Huawei.  None the less, my Android devices are also updating.  So this may be a new feature that Android has extended to us.  

For example, my micro SDCards that used to work, do not work as expected after updating Android, and causes the Android system to reboot over and over again while checking the micro SDCard!  In my opinion this is very bad behavior on Android's part for software with version 10 point something something (insert card = reboot).  Do you agree?

**Comment by JanuszChmiel** [comment]
I AM using up to date Termux packages. By typing
Apt update
Apt upgrade
And I will rather check Termux on Google Play store.
I have also updated Termux packages today Bash also introduced some update.
But to have a positive mood. Debian buster and Ubuntu-20.04 installed by using proot-distro work. So there is not deep problem, which would cause proot developers to make many complex changes inside Proot source code. 


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
Yes, I agree with you.
May be, that you will have to backup yours SD cart and reformat it after this update. Huavei 8 and 7.1 kernel introduced other interesting feature. Partial case file system insensitivity.
Fortunately for Me, Mr Bednarski have been so kind and patient, that he has connected remotely to my mobile phone by using Tmate SSZH app, which has big advantage.
It is not necessary to have static public IP address and it is not necessary to give IP address to someone else. Tmate generate strong encryption key, string as a identifier and it is possible to monitor and work with Termux by using ssh.
I absolutely like Dropbear for Termux. It is much more simple than Dropbear for other official Linux distros. Dropbear for Termux is preconfigured so it is possible to only type dropbear and user can connect.Fortunately for Me, I have also finally found reliable and very blind friendly SSH client app for Windows. Its name is Teraterm. It have been built and compiled by using Microsoft Visual C 2008 with 100 % accessible app GUI. It is better for Me thanPUtty for Windows.
App is fast, stable, and it is possible to have logs or long textual buffer with all screens output.
SSH client is The tool which all not only visually impaired Termux users or developers should have. To be able to look at some important output messages.
I AM now running Ubuntu-20.04 with Orca, Ratpoison and with goodvipes GTK3 compatible Internet radio. To have A little job, I will try to extend this opensource app by adding Czech state radio stations. Its C code is very friendly, much more friendly than complex gnome-session so I will be able to change station names and I will be even able to change predefined stream direct links. It will be a little tasks for Me. I will add always number near to The first character of every station name.
So I will have a good player. In fact, it would be excellent player. Sure, modern players support station search, but development of such as C app is out of my scopes for Now. I can do only little modiffications.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
Thanks to this useful Bash script here, I can use Ratpoison even to display application run dialog, Orca run automatically. Sure. Orca will not work if I will not start ratpoison by typing
Dbus-run-session ratpoison &
Some apps require dbus-run-session some not, user must determine. Gedit do not require, but some GTk apps yes.

https://github.com/stormdragon2976/strychnine



-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
It appears two factors were also possibly involved in generating this error after updating packages:  
1. Android update
1. Termux app update

Both are now updated and the error is gone!  I have just tested two successful installs, one with `setupTermuxArch i armv7l` and another with `setupTermuxArch v i x86`.  Both installations appear to be working as expected on the same smartphone.

**Comment by JanuszChmiel** [comment]
Very interesting. I have not got new updates. I will try to reinstall Termux.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
I have A perfect news.
After you have done some main setup script update, everything work as expected without issues. I would like to congratulate you that you and other community members have developer complex routines which are able to publicly signing keys, import keys and inject unwanted ArchLinux packages and repo.
When I Am watching output, I Am deeply and deeply appreciating you and other participants. Because I know, how many tasks must be performed to prepare fully functioning ArchLinux. And because ArchLinux repos are newer and newer, it is necessary to find new routines to make this project functioning and live.
So thank you again.
I will rather use ArchLinux. Debian stable contain much older packages and such it is not so good for my experiments while building new apps.
Very well done and thank you again.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
And I have a next nice words for you. Makeyay script work fully automatic. No user input needed. Only typing makeyay and package have been built.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz
