### ISSUE TITLE
How to get more optimization? 

### ISSUE THREAD

**Issue by Yisus7u7** [TermuxArch/TermuxArch#41]
I'm using termux arch with xfce4, performance has been low, especially that of browsers, there is some way to have more performance?, for example, disable the proot clipboard with the host, or things done,?

**Comment by SDRausty** [comment]
The command [`timings`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L1191) is added to assist with optimization.
