### ISSUE TITLE
Hown to run aarch command without login direct from termux

### ISSUE THREAD

**Issue by tathastu871** [TermuxArch/TermuxArch#42]

**Comment by SDRausty** [comment]
~ $ startarch help

startarch  start Arch Linux in Termux PRoot with root login.  This account is reserved for system administration.  Please exercise caution when using the system administrator account.

startarch c[ommand] command  run Arch Linux command from Termux as root login.  Quoting multiple commands can assit when passing multiple arguments:  startarch c 'whoami ; cat -n /etc/pacman.d/mirrorlist'.  Please pass commands through the system administrator account with caution.

startarch el[ogin] | eu[ser] user  login as user.  Use alternate elogin or euser option to login as user.  This option is preferred for working with programs that have already been installed, and for working with the 'git' command.  Please use startarch c 'addauser user' first to create this user and the user's home directory.

startarch l[ogin] | u[ser] user  login as user.  This option is preferred when installing software from a user account with the 'sudo' command, and when using commands such as 'makeaurhelpers', 'makepkg' and 'makeyay'.  Please use 'addauser user' first to create this user and the user's home directory.

startarch r[aw]  construct the startarch proot statement from exec.../bin/.  For example startarch r su will exec su in Arch Linux.  See variable PROOTSTMNT for more options;  Please share your thoughts at https://github.com/TermuxArch/TermuxArch/issues and https://github.com/TermuxArch/TermuxArch/pulls.

startarch s[u] user command  login as user and execute command.  This option is preferred when installing software from a user account with the 'sudo' command, and when using commands such as 'makeaurhelpers', 'makepkg' and 'makeyay'.  Quoting multiple commands can assit when passing multiple arguments:  startarch s user 'whoami ; cat -n /etc/pacman.d/mirrorlist'.  Please use startarch c 'addauser user' first to create a login and the login's home directory.

startarch h 2.0.1085: DONE 🏁
~ $
