### ISSUE TITLE
Unable to access android files after update to Android 11

### ISSUE THREAD

**Issue by gadepall** [TermuxArch/TermuxArch#43]
Following is the output of
cd storage/shared

bash: cd: storage/shared: No such file or directory

proot-ubuntu is able to access the android files

**Comment by SDRausty** [comment]
Adding [` -b /storage`](https://github.com/TermuxArch/TermuxArch/commit/b403bfd11f6fc9a59b12d6a06c5373a6e88aa3c3#diff-9b2bb1a83c2a2f0a8b09bdf8fe7a5aa9671ad530a746c90fda23c3e623149c82R107) has resolved this issue.  Thank you @gadepall for bringing this to my attention.
