### ISSUE TITLE
install doc links to SDRausty repo

### ISSUE THREAD

**Issue by cubetronic** [TermuxArch/TermuxArch#45]
this is confusing. and i think it's not intended. this is similar to what i saw in BuildAPKs.

TermuxArch/TermuxArch links to an install doc that says to clone SDRausty/TermuxArch

i notice, as of right now, this repo was updated 9 days ago, but the SDRausty/TermuArch repo was updated 25 days ago.

i think it would be best to make the doc link to the same repo, not across repos.

i also think it would help to clarify, somewhere, what the difference between repos is. like, is one a dev repo and one a stable repo? or is one just lagging?

**Comment by SDRausty** [comment]
> best to make the doc link to the same repo, not across repos.

I agree that the documentation can be improved; PRs are welcome.

> is one a dev repo and one a stable repo? or is one just lagging?

They are rolling releases; and the release process deserves a little improvement.

> lagging?

Unfortunantly, that's correct.
