### ISSUE TITLE
pc gradle - error: target not found

### ISSUE THREAD

**Issue by cubetronic** [TermuxArch/TermuxArch#46]
i'm trying to install gradle, but it's not working.

```
[root19:06/]$ pc gradle
==> Running TermuxArch command pc gradle v2.0.1086...
error: target not found: gradle

 TermuxArch WARNING:  Generated script signal 1 near or at line number 83 by '$SUDOCONF'!

TermuxArch pc gradle 2.0.1086: DONE 📱 🏁

[root19:23/]$
```

i tried that according to the suggestion here:

https://github.com/BuildAPKs/buildAPKs/issues/13#issuecomment-562974133

**Comment by cubetronic** [comment]
i exited then logged in using `startarch l user` then it worked

**Comment by cubetronic** [comment]
no, it did not work. same result.

**Comment by cubetronic** [comment]
`pacman -Ss gradle` produces no results

**Comment by cubetronic** [comment]
in fact, https://archlinuxarm.org/packages has 0 results for gradle. of course it is over at https://archlinux.org/packages/?sort=&q=gradle&maintainer=&flagged= but that doesn't help me

**Comment by SDRausty** [comment]
>  https://archlinux.org/packages/?sort=&q=gradle&maintainer=&flagged= but that doesn't help me

Please try `yay gradle` after running `makeyay`.

**Comment by SDRausty** [comment]
> i'm trying to install gradle, but it's not working.

I've just found a very interesting alternative at https://github.com/sdkman which works:
```
curl -s "https://get.sdkman.io" > sdk.install.bash
bash sdk.install.bash
```

**Comment by SDRausty** [comment]
> i'm trying to install gradle, but it's not working.

I've just found a very interesting alternative at https://github.com/sdkman which works:
```
curl -s "https://get.sdkman.io" > sdk.install.bash
bash sdk.install.bash
```
