### ISSUE TITLE
how to backup my termux arch installation?

### ISSUE THREAD

**Issue by T4P4N** [TermuxArch/TermuxArch#47]
I need to migrate my termux arch installation to other 
a device. Is there any way to backup & restore termux & termux arch installation,  I checked au it seems like it only backups packages not the configuration files.

**Comment by SDRausty** [comment]
> au it seems like it only backups packages 

This is correct; That's its' function. It only attempts to backup Termux packages.

> how to backup my termux arch installation?

Search example: `backup site:wiki.termux.com`

> https://wiki.termux.com/wiki/Backing_up_Termux

Create example:  `tar -zcf arch.archive.tar.gz ~/arch`

Extract example:  `tar -xvf arch.archive.tar.gz`

**Comment by T4P4N** [comment]
@SDRausty Thank you very much for answering my query. I also have few more queries:
- Systemd doesn't work in termux arch, any alternative available for that, which works in termux-arch, like runit/sv in termux?
- Is audio working now in termux-arch? 
- Can i use AUR pkgs in termux-arch now!?
- What should i use for managing global python packages? pacman or pip?
- Postgres & mysql/mariadb doesn't work correctly in termux-arch, so i use termux for postgres & mysql.
- I can't able to change my shell to zsh
- how to create/update/delete/list users in termux-arch ?
I'm asking you all these queries cause i haven't found any FAQ section in Readme.

**Comment by SDRausty** [comment]
> Is there any way to backup & restore termux & termux arch installation

https://wiki.termux.com/index.php?search=backup
