### ISSUE TITLE
Real root

### ISSUE THREAD

**Issue by dnut** [TermuxArch/TermuxArch#48]
For users with rooted phones, why not use actual root instead of proot? Wouldn't it be better to avoid the weaknesses of proot?

**Comment by SDRausty** [comment]
> For users with rooted phones, why not use actual root instead of proot? 

PRoot should NOT be used with rooted smartphones.  

> Wouldn't it be better to avoid the weaknesses of proot?

The command [`chroot`](https://tldp.org/HOWTO/Chroot-BIND-HOWTO-1.html) avoids these.

**Comment by dnut** [comment]
> PRoot should NOT be used with rooted smartphones.
This is exactly my point. 

> The command chroot avoids these.
So you're saying it would be easy to implement my recommendation?

I don't understand why you closed the issue.
