### ISSUE TITLE
is there way to get a sound working

### ISSUE THREAD

**Issue by layaachmad** [TermuxArch/TermuxArch#51]
the pulseaudio not `working` how could i get working `pulseaudio` on it!

**Comment by SDRausty** [comment]
Use Pulse in Termux;

add (or uncomment) `load-module module-native-protocol-tcp` in `$PREFIX/etc/pulse/default.pa`

Run Pulse as a daemon from Termux; `pulseaudio -D --disallow-exit=1`

And in proot; `export PULSE_SERVER=tcp:127.0.0.1:4713`

This will work for anything that uses pulseaudio for output.

You can use XSDL server as that comes with a pulse server, which can be exported like last command above.

This should be automated when using the `visualorca` options with [`setupTermuxArch`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch).

**Comment by SDRausty** [comment]
Use Pulse in Termux;

add (or uncomment) `load-module module-native-protocol-tcp` in `$PREFIX/etc/pulse/default.pa`

Run Pulse as a daemon from Termux; `pulseaudio -D --disallow-exit=1`

And in proot; `export PULSE_SERVER=tcp:127.0.0.1:4713`

This will work for anything that uses pulseaudio for output.

You can use XSDL server as that comes with a pulse server, which can be exported like last command above.

Originally posted by [u/dutchofburdoc](https://www.reddit.com/user/DutchOfBurdock/) in [TERMUX PROOT WITH SOUND](https://www.reddit.com/r/termux/comments/o7ms3q/termux_proot_with_sound/)


This process is automated when using the `visualorca` options with [`setupTermuxArch`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch).
