### ISSUE TITLE
Добавте поддержку opencl андроид

### ISSUE THREAD

**Issue by AlexanderNagibator22888** [TermuxArch/TermuxArch#52]
В Ubuntu https://github.com/MFDGaming/ubuntu-in-termux hashcat работал с opencl на mali g51 а в arch linux нет

**Comment by SDRausty** [comment]
Не могли бы вы подробнее рассказать о своей поддержке предложения opencl для Android?  

> В Ubuntu https://github.com/MFDGaming/ubuntu-in-termux hashcat работал с opencl на mali g51 а в arch linux нет


не могли бы вы указать последовательность установки пакетов, которую вы использовали?

**Comment by AlexanderNagibator22888** [comment]
Я поставил arch linux в терукс потом hashcat после установки я попробовал
запустить hashcat но мне выдаёт ошибку

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

clGetDeviceIDs(): CL_DEVICE_NOT_FOUND

No devices found/left.

после чего я попробовал поставить пакет opencl-driver но ошибка та же самая
я пробовал ставить все драйвера из репозитория alarm которые начинаются
на xf86, mali, odroid но всё без результатов
