### ISSUE TITLE
Add a option to start termuxarch with sharedtmp

### ISSUE THREAD

**Issue by PermisosDev** [TermuxArch/TermuxArch#55]
Related: #25 
Related: https://github.com/termux/proot-distro/issues/48

Implementing shared tmp could be able to run graphical applications in termux arch.

if this is not possible, answer the issue.

**Comment by SDRausty** [comment]
> Implementing shared tmp could be able to run graphical applications in termux arch.

This commit https://github.com/TermuxArch/TermuxArch/commit/9018b20cc8828c173ca1d39d5275b917170b0714 implements your suggention;  Thank you for commenting 🎵 🎶
