### ISSUE TITLE
TermuxArch WARNING:  Generated script signal 1 near or at line number 211 by '[['!

### ISSUE THREAD

**Issue by OvsS325** [TermuxArch/TermuxArch#58]
"TermuxArch WARNING:  Generated script signal 1 near or at line number 211 by '[['!"
Every time I type "bash setupTermuxArch.sh" I get this error, why?

**Comment by SDRausty** [comment]
> "TermuxArch WARNING: Generated script signal 1 near or at line number 211 by '[['!"
Every time I type "bash setupTermuxArch.sh" I get this error, why?

Thank you for sharing;  This commit https://github.com/TermuxArch/TermuxArch/commit/58c4aebcb32936fdcff073951bef6135034d4f12 resolves the error.
