### ISSUE TITLE
QEMU

### ISSUE THREAD

**Issue by Vixeliz** [TermuxArch/TermuxArch#61]
Hello! Thanks for this amazing project. However I was wondering if there is any way to get more performance out of qemu? Via more cores or something?

**Comment by SDRausty** [comment]
>However I was wondering if there is any way to get more performance out of qemu? 

I am sure there is;  We want to go upstream to get more performance out of qemu afaik.

**Comment by Vixeliz** [comment]
Hmmm ok maybe will open an issue on qemu repo then at some point. You can close this if you'd like
