### ISSUE TITLE
sdkmanager "emulator" missing from TermuxArch but is available on normal Arch Linux installs

### ISSUE THREAD

**Issue by shipsywor** [TermuxArch/TermuxArch#62]
##  TermuxArch 

Install TermuxArch on Termux.

Inside `/root/` of Arch or Inside `/data/data/com.termux/files/home`:

Create and enter `android_sdk`

Download `cmdline-tools`

```
wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
```
unzip it.

Find the sdkmanager inside `cmdline-tools/tools/bin`
(Note: Create `tools` directory inside `cmdline-tools` that we unzipped and copy all contents to `tools`)

On termux:

Run `sh sdkmanager --list` : You will not find any emulator listed.
Similarly, do `sh sdkmanager emulator` : You will not be able to download emulator as its not listed.

## For normal Arch Linux on Laptop

Download cmdline-tools as above and do run the same steps as above. You will see we are able to see emulator listed and able to downloaded with sdkmanager.

## Additional Notes

Why is it working differently and is there a way to make sdkmanager work normally on TermuxArch? That is it should have all packages listed of sdkmanager that are seen on normal Arch Linux

**Comment by raccoonsteven** [comment]
Pipx install sdkmanager

After it does, you can install the emulator.
