### ISSUE TITLE
Elaborate difference from proot-distro please

### ISSUE THREAD

**Issue by ujjvlh** [TermuxArch/TermuxArch#66]
The `README` should include how this is different from installing Arch via `proot-distro`.

**Comment by SDRausty** [comment]
>Elaborate difference from proot-distro please

>[ No need for another proot distro.](https://www.reddit.com/r/termux/comments/rwjlbz/about_qemu/)

The shell script [`setupTermuxArch.sh`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch.sh) was not the first one to help users with Termux PRoot;  One of the reasons why [TermuxArch](https://termuxarch.github.io/TermuxArch/) came into being is to ease configuring and installing [Linux distributions](https://www.ecosia.org/search?q=Linux+distributions) in Termux on handhelds and similar devices with and without [QEMU](https://github.com/qemu), and much more!

Later we were blessed to see proot-distro appear also, for those of us who choose to be Termuxed, and are at times glued to our Android screens with sound.  I wonder whether history was written in a similar way?

**Comment by SDRausty** [comment]
https://github.com/termux/proot/issues/216
