### ISSUE TITLE
```addauser``` command returns error

### ISSUE THREAD

**Issue by NotteShock** [TermuxArch/TermuxArch#67]
Also not related to this issue but when installing yay, i type the password that i set earlier and meh that doesn't work

**Comment by NotteShock** [comment]
the screenshot doesn't work, so here's the error:
```
root07:03~$ addauser sang
/usr/local/bin/addauser: line 78: syntax error near unexpected token `;'
```

**Comment by SDRausty** [comment]
>`addauser sang`

Commit https://github.com/TermuxArch/TermuxArch/commit/34ef69abffdf6e74a5f18251bc4822858bf99770 resolves this error.

>when installing yay, i type the password that i set and meh that doesn't work

There should not any passwords required at all in order to use `makeyay` and `yay`;  What is meh?  Do you mean python-meh?

**Comment by NotteShock** [comment]
not, "meh" is just a random word
