### ISSUE TITLE
Libreoffice

### ISSUE THREAD

**Issue by dk009dk** [TermuxArch/TermuxArch#7]
Libreoffice isn't working

When run on terminal it shows this error

ERROR: /proc not mounted - LibreOffice is unlikely to work well if at all

**Comment by SDRausty** [comment]
@dk009dk see if working with function `_PR00TSTRING_` in file [knownconfigurations.bash](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash) helps.

**Comment by SDRausty** [comment]
> ERROR: /proc not mounted 

bind is like mount

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/19d112ef96ab846aa8c74245407d2e7b947d7a75 rewrote memory integration.  It does't touch /proc though.  File [knownconfigurations.bash](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash) has information regarding proot binds/mounts.

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/19d112ef96ab846aa8c74245407d2e7b947d7a75 rewrote memory integration again.  File [knownconfigurations.bash](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash) has information regarding proot binds/mounts.

**Comment by SDRausty** [comment]
This pull https://github.com/TermuxArch/TermuxArch/pull/12 request contributed by @petkar resolves this issue:

> [tested it and Libreoffice starts up perfectly now with no additional tweaking required.](https://github.com/SDRausty/TermuxArch/issues/242)
