### ISSUE TITLE
Installer interrupts wget to check the MD5 hash, and fails due to it interrupting its own download

### ISSUE THREAD

**Issue by yoshiboyadvance** [TermuxArch/TermuxArch#74]

**Comment by SDRausty** [comment]
h)

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/587f86a59df565bc7e613b828e6423c1ea5c2670 commit resolves issue https://github.com/TermuxArch/TermuxArch/issues/74.
