### ISSUE TITLE
Termux crashes when using chsh to change shell to startarch

### ISSUE THREAD

**Issue by yoshiboyadvance** [TermuxArch/TermuxArch#75]
https://imgur.com/a/VcbaEWu

**Comment by SDRausty** [comment]
> https://imgur.com/a/VcbaEWu

Using GitHub like in this example id preferred and is much easier to read:

![Termux crashes when using chsh to change shell to startarch](https://raw.githubusercontent.com/TermuxArch/imgsTermuxArch/master/screenshots/TermuxArch/TermuxArch/issues/75/4JBCkzp.gif)

You are not using `chsh` correctly @yoshiboyadvance; Please see https://github.com/SDRausty/TermuxArch/issues/212 for more information about setting the default shell in Termux and post your comments there, and here.

I would like setupTermuxArch to be as easy to use as possible and the login topic can possibly be simplified, and automated much easier with a user veiwpoint like yours;  Please share your progress here in these issuse.

Please `cat laptop.sh`, and can you outline the steps that you used to get to the point in the video?
