### ISSUE TITLE
Pacman failing to install new packages

### ISSUE THREAD

**Issue by Yrosenz** [TermuxArch/TermuxArch#82]
I have installed a new instance of arch on my Termux using the latest scrip.
Right after install and run one pass of update trued to install corgi, but installation finished with errors.
To make sure that the error are not related to the armarchlinux image I have tried to install again using a previous version of the image, and the same results.
[pacman-xorg-error.txt](https://github.com/TermuxArch/TermuxArch/files/8110948/pacman-xorg-error.txt)

**Comment by SDRausty** [comment]
@Yrosenz thank you for sharing.  I CANNOT confirm this with `pacman` after testing today, but I did run into a very similar error using an aur repository the other night.  Can you please ask upstream what is going on with the `pacman` command on your device?

**Comment by Yrosenz** [comment]
addauser also failed on the same instance.
Today I installed a new instance but using a version of the script that I saved on my sd, and all is working fine. 
I couldn't find how to check the version of both.

**Comment by SDRausty** [comment]
> all is working fine

great

> installed a new instance

The command `setupTermuxArch re` refreshes the TermuxArch files to the newest version, Unless the installation itself became broken, installing a new instance should not be needed ar refreshing should suffic.

If you have ample space on device, setting `KEEP=0` and `USECACHEDIR=0` will populate a new instance from the cache directory once the installation files are placed into the cache directory.

> how to check the version 

TermuxArch prints the version during runtime.  The command `grep VERSIONID= setupTermuxArch` can also be used:

`VERSIONID=2.1.15`
