### ISSUE TITLE
Error: TEXDIR - Unbound Variable

### ISSUE THREAD

**Issue by anfaro** [TermuxArch/TermuxArch#84]
![Screenshot_20220223-003312.png](https://user-images.githubusercontent.com/39028530/155186836-8b2fc4c2-50bf-450b-8092-80113aef5b3d.png)

**Comment by alimuratbz** [comment]
I have same problem

**Comment by SDRausty** [comment]
@anfaro and @alimuratbz thank you for sharing.  This https://github.com/TermuxArch/TermuxArch/commit/0f698934cb80772147aa7e2376cf561254553982 commit resolves TEXDIR - Unbound Variable.

Sorry that you experienced the growing pains associated with implementing this new command, `tlmgrinstaller`.  It installs Texlive which is a typesetting tool that can produce a letter to books, 360mb min to <7gb max.  Good luck with your writing carreers.
