### ISSUE TITLE
Libreoffice doesn't work.

### ISSUE THREAD

**Issue by Yrosenz** [TermuxArch/TermuxArch#87]
I've just installed Libreoffice and can't make it work.
It fails with same error message previous reported:
ERROR: /proc not mounted.
I checked the fix provided by petkar is not present on the last archlinuxconfig.bash.
It should be? It can be that it has been added to another file?

**Comment by SDRausty** [comment]
>It should be? It can be that it has been added to another file?

Yes, it should be, and Libreoffice should be working fine. 
Thank you for reporting.  Can you [PR](https://github.com/TermuxArch/TermuxArch/pulls) it please if it is missing?

>can be that it has been added to another file?

Please use `grep search *ash` to search all the BASH source code files.

**Comment by SDRausty** [comment]
Files `fbindsfunctions.bash` and `initkeyfunctions.bash` were recently created as file `archlinuxconfig.bash` had grown too large.  Some of the functions are now in one of these two files.  When you find the function that you are seeking, moving it back to `archlinuxconfig.bash` should resolve the error if this is the case.  Please share as soon as possible so a patch can be uploaded asap.

**Comment by SDRausty** [comment]
@Yrosenz if you are still having trouble with this https://github.com/TermuxArch/TermuxArch/issues/87 issue, please comment here.

**Comment by SDRausty** [comment]
The recently developed [`makeaurhelpers`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L664&&#L1054) command might also be helpfull in streamlining this issue;  Testing for `makeaurhelpers` is requested as this command  is now undepreciated with recent commits and is also significantly expanded.  

Please see `makeaurhelpers help` for more information about its new features that build and package Arch Linux AUR packages on handheld Android devices in Termux with PRoot and QEMU.
