### ISSUE TITLE
strange messages at the end of installation.

### ISSUE THREAD

**Issue by Yrosenz** [TermuxArch/TermuxArch#89]
Are you guys aware of this:
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_IL.UTF-8): No such file or directory
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_IL.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (en_IL.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (en_IL.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (en_IL.UTF-8): No such file or directory
bash: $'\E[?25h\E[1': command not found
bash: 48: command not found
bash: 5: command not found
bash: 138m: command not found
bash: 32mCommand: command not found
bash: 32msetupTermuxArch.sh manual: command not found
bash: 32mversion: command not found
bash: 34m:: command not found
bash: 32mDONE: command not found
bash: $'\E]2': command not found
bash: setupTermuxArch.sh: command not found

**Comment by SDRausty** [comment]
Does this error still persist?

**Comment by SDRausty** [comment]
Thank you for sharing @Yrosenz; the strange message is resolved with this https://github.com/TermuxArch/TermuxArch/commit/6228fd0190f18196970aa3cfedac6d9fb45ca560#diff-27ed3efd28bce5fba9bc8ba42bdf785b1790b3d8b5bcf312f48f5ad3fbd2f065L415 commit.

**Comment by SDRausty** [comment]
This error was related to having the `locale-gen` automation work in TermuxArch once more.
