### ISSUE TITLE
accessibility for blind users?

### ISSUE THREAD

**Issue by mjonsson1986** [TermuxArch/TermuxArch#91]
i found this closed issue:
https://github.com/TermuxArch/TermuxArch/issues/34

what are the progress? of this?

**Comment by SDRausty** [comment]
>accessibility for blind users?

Expanding setupTermuxArch so visually impaired users can install Orca screen reader (assistive technology) and have VNC support added easily. #34
>what are the progress? of this?

Please see [A few questions about Arch Linux in Termux PRoot #59](https://github.com/SDRausty/TermuxArch/issues/59) for some more information.

The recently undepreciated [`makeaurhelpers`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L664&&#L1054) command might also be helpfull in streamlining this issue;  Testing for `makeaurhelpers` is requested as this command  is undepreciated with recent commits and is now significantly expanded.  

Please see `makeaurhelpers help` for more information about its amazing new features that build and package Arch Linux AUR packages on handheld Android devices in Termux with PRoot and QEMU.

**Comment by SDRausty** [comment]
> i found this closed issue:

> Expanding setupTermuxArch so visually impaired users can install Orca screen reader (assistive technology) and have VNC support added easily. #34

Which part/section in issue #34 is referred to to please?

**Comment by SDRausty** [comment]
[referred to](https://github.com/SDRausty/termux-archlinux/issues/92)

**Comment by SDRausty** [comment]
severe Seamonkey internet suite crash occurred #92 https://github.com/SDRausty/termux-archlinux/issues/92

**Comment by SDRausty** [comment]
https://github.com/SDRausty/termux-archlinux/issues/66

**Comment by SDRausty** [comment]
Let's expand setupTermuxArch so users can install Orca screen reader (assistive technology) and also have VNC support added easily. #66

https://github.com/SDRausty/termux-archlinux/issues/66
